openapi: 3.0.1
info:
  title: Hephaestus API
  description: API documentation for the Hephaestus application server.
  contact:
    name: Felix T.J. Dietrich
    email: felixtj.dietrich@tum.de
  license:
    name: MIT License
    url: https://github.com/ls1intum/Hephaestus/blob/develop/LICENSE
  version: 0.0.1
servers:
- url: /
  description: Default Server URL
paths:
  /admin/users/teamadd/{login}/{teamId}:
    put:
      tags:
      - admin
      operationId: addTeamToUser
      parameters:
      - name: login
        in: path
        required: true
        schema:
          type: string
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
  /admin/teams:
    put:
      tags:
      - admin
      operationId: createTeam
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TeamInfo"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamInfo"
  /admin/config/repositories:
    post:
      tags:
      - admin
      operationId: updateRepositories
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  type: string
  /user/{login}/profile:
    get:
      tags:
      - user
      operationId: getUserProfile
      parameters:
      - name: login
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
  /team/all:
    get:
      tags:
      - team
      operationId: getTeams
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TeamInfo"
  /leaderboard:
    get:
      tags:
      - leaderboard
      operationId: getLeaderboard
      parameters:
      - name: after
        in: query
        required: false
        schema:
          type: string
          format: date
      - name: before
        in: query
        required: false
        schema:
          type: string
          format: date
      - name: team
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LeaderboardEntry"
  /admin:
    get:
      tags:
      - admin
      operationId: admin
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
  /admin/users:
    get:
      tags:
      - admin
      operationId: getUsersAsAdmin
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserTeams"
  /admin/me:
    get:
      tags:
      - admin
      operationId: getGretting
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthUserInfo"
  /admin/config:
    get:
      tags:
      - admin
      operationId: getConfig
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdminConfig"
  /admin/users/teamremove/{login}/{teamId}:
    delete:
      tags:
      - admin
      operationId: removeTeamFromUser
      parameters:
      - name: login
        in: path
        required: true
        schema:
          type: string
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
  /admin/teams/{teamId}:
    delete:
      tags:
      - admin
      operationId: deleteTeam
      parameters:
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamInfo"
components:
  schemas:
    PullRequestInfo:
      required:
      - additions
      - commentsCount
      - deletions
      - htmlUrl
      - id
      - isDraft
      - isMerged
      - number
      - state
      - title
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: integer
          format: int32
        title:
          type: string
        state:
          type: string
          enum:
          - OPEN
          - CLOSED
        isDraft:
          type: boolean
        isMerged:
          type: boolean
        commentsCount:
          type: integer
          format: int32
        author:
          $ref: "#/components/schemas/UserInfo"
        labels:
          type: array
          items:
            $ref: "#/components/schemas/LabelInfo"
        assignees:
          type: array
          items:
            $ref: "#/components/schemas/UserInfo"
        repository:
          $ref: "#/components/schemas/RepositoryInfo"
        additions:
          type: integer
          format: int32
        deletions:
          type: integer
          format: int32
        mergedAt:
          type: string
          format: date-time
        closedAt:
          type: string
          format: date-time
        htmlUrl:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    LabelInfo:
      required:
      - color
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        color:
          type: string
    AdminConfig:
      required:
      - repositoriesToMonitor
      type: object
      properties:
        repositoriesToMonitor:
          uniqueItems: true
          type: array
          items:
            type: string
    UserProfile:
      required:
      - contributedRepositories
      - firstContribution
      - userInfo
      type: object
      properties:
        userInfo:
          $ref: "#/components/schemas/UserInfo"
        firstContribution:
          type: string
          format: date-time
        contributedRepositories:
          type: array
          items:
            $ref: "#/components/schemas/RepositoryInfo"
        reviewActivity:
          type: array
          items:
            $ref: "#/components/schemas/PullRequestReviewInfo"
        openPullRequests:
          type: array
          items:
            $ref: "#/components/schemas/PullRequestInfo"
    PullRequestReviewInfo:
      required:
      - codeComments
      - htmlUrl
      - id
      - isDismissed
      - state
      type: object
      properties:
        id:
          type: integer
          format: int64
        isDismissed:
          type: boolean
        state:
          type: string
          enum:
          - COMMENTED
          - APPROVED
          - CHANGES_REQUESTED
          - UNKNOWN
        codeComments:
          type: integer
          format: int32
        author:
          $ref: "#/components/schemas/UserInfo"
        pullRequest:
          $ref: "#/components/schemas/PullRequestBaseInfo"
        htmlUrl:
          type: string
        submittedAt:
          type: string
          format: date-time
    RepositoryInfo:
      required:
      - htmlUrl
      - id
      - name
      - nameWithOwner
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        nameWithOwner:
          type: string
        description:
          type: string
        htmlUrl:
          type: string
    UserTeams:
      required:
      - id
      - login
      - name
      - teams
      - url
      type: object
      properties:
        id:
          type: integer
          format: int64
        login:
          type: string
        name:
          type: string
        url:
          type: string
        teams:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/TeamInfo"
    PullRequestBaseInfo:
      required:
      - htmlUrl
      - id
      - isDraft
      - isMerged
      - number
      - state
      - title
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: integer
          format: int32
        title:
          type: string
        state:
          type: string
          enum:
          - OPEN
          - CLOSED
        isDraft:
          type: boolean
        isMerged:
          type: boolean
        repository:
          $ref: "#/components/schemas/RepositoryInfo"
        htmlUrl:
          type: string
    AuthUserInfo:
      type: object
      properties:
        name:
          type: string
        roles:
          type: array
          items:
            type: string
    UserInfo:
      required:
      - avatarUrl
      - htmlUrl
      - id
      - login
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        login:
          type: string
        avatarUrl:
          type: string
        name:
          type: string
        htmlUrl:
          type: string
    TeamInfo:
      required:
      - color
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        color:
          type: string
    LeaderboardEntry:
      required:
      - numberOfApprovals
      - numberOfChangeRequests
      - numberOfCodeComments
      - numberOfComments
      - numberOfReviewedPRs
      - numberOfUnknowns
      - rank
      - score
      - user
      type: object
      properties:
        rank:
          type: integer
          format: int32
        score:
          type: integer
          format: int32
        user:
          $ref: "#/components/schemas/UserInfo"
        numberOfReviewedPRs:
          type: integer
          format: int32
        numberOfApprovals:
          type: integer
          format: int32
        numberOfChangeRequests:
          type: integer
          format: int32
        numberOfComments:
          type: integer
          format: int32
        numberOfUnknowns:
          type: integer
          format: int32
        numberOfCodeComments:
          type: integer
          format: int32
