openapi: 3.0.1
info:
  title: Hephaestus API
  description: API documentation for the Hephaestus application server.
  contact:
    name: Felix T.J. Dietrich
    email: felixtj.dietrich@tum.de
  license:
    name: MIT License
    url: https://github.com/ls1intum/Hephaestus/blob/develop/LICENSE
  version: 0.0.1
servers:
- url: /
  description: Default Server URL
paths:
  /workspace/user/{login}/team/{teamId}:
    put:
      tags:
      - workspace
      operationId: addTeamToUser
      parameters:
      - name: login
        in: path
        required: true
        schema:
          type: string
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
    delete:
      tags:
      - workspace
      operationId: removeUserFromTeam
      parameters:
      - name: login
        in: path
        required: true
        schema:
          type: string
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
  /workspace/teams:
    put:
      tags:
      - workspace
      operationId: createTeam
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TeamInfo"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamInfo"
  /workspace/teams/autoassign:
    put:
      tags:
      - workspace
      operationId: automaticallyAssignTeams
      responses:
        "200":
          description: OK
  /workspace/team/{teamId}/repository/{repositoryOwner}/{repositoryName}:
    post:
      tags:
      - workspace
      operationId: addRepositoryToTeam
      parameters:
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: repositoryOwner
        in: path
        required: true
        schema:
          type: string
      - name: repositoryName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamInfo"
    delete:
      tags:
      - workspace
      operationId: removeRepositoryFromTeam
      parameters:
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: repositoryOwner
        in: path
        required: true
        schema:
          type: string
      - name: repositoryName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamInfo"
  /workspace/team/{teamId}/label/{repositoryId}/{label}:
    post:
      tags:
      - workspace
      operationId: addLabelToTeam
      parameters:
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: repositoryId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: label
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamInfo"
  /workspace/repositories/{owner}/{name}:
    post:
      tags:
      - workspace
      operationId: addRepositoryToMonitor
      parameters:
      - name: owner
        in: path
        required: true
        schema:
          type: string
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
    delete:
      tags:
      - workspace
      operationId: removeRepositoryToMonitor
      parameters:
      - name: owner
        in: path
        required: true
        schema:
          type: string
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
  /sessions:
    get:
      tags:
      - session
      operationId: getSessions
      parameters:
      - name: login
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Session"
    post:
      tags:
      - session
      operationId: createSession
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Session"
  /messages/{sessionId}:
    get:
      tags:
      - message
      operationId: getMessages
      parameters:
      - name: sessionId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
    post:
      tags:
      - message
      operationId: createMessage
      parameters:
      - name: sessionId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
  /workspace/users:
    get:
      tags:
      - workspace
      operationId: getUsersWithTeams
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserTeams"
  /workspace/repositories:
    get:
      tags:
      - workspace
      operationId: getRepositoriesToMonitor
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /user/{login}/profile:
    get:
      tags:
      - user
      operationId: getUserProfile
      parameters:
      - name: login
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfile"
  /team/all:
    get:
      tags:
      - team
      operationId: getTeams
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TeamInfo"
  /meta:
    get:
      tags:
      - meta
      operationId: getMetaData
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MetaData"
  /leaderboard:
    get:
      tags:
      - leaderboard
      operationId: getLeaderboard
      parameters:
      - name: after
        in: query
        required: true
        schema:
          type: string
          format: date-time
      - name: before
        in: query
        required: true
        schema:
          type: string
          format: date-time
      - name: team
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/LeaderboardEntry"
  /workspace/team/{teamId}:
    delete:
      tags:
      - workspace
      operationId: deleteTeam
      parameters:
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamInfo"
  /workspace/team/{teamId}/label/{labelId}:
    delete:
      tags:
      - workspace
      operationId: removeLabelFromTeam
      parameters:
      - name: teamId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      - name: labelId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TeamInfo"
  /user:
    delete:
      tags:
      - user
      operationId: deleteUser
      responses:
        "200":
          description: OK
components:
  schemas:
    PullRequestInfo:
      required:
      - additions
      - commentsCount
      - deletions
      - htmlUrl
      - id
      - isDraft
      - isMerged
      - number
      - state
      - title
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: integer
          format: int32
        title:
          type: string
        state:
          type: string
          enum:
          - OPEN
          - CLOSED
        isDraft:
          type: boolean
        isMerged:
          type: boolean
        commentsCount:
          type: integer
          format: int32
        author:
          $ref: "#/components/schemas/UserInfo"
        labels:
          type: array
          items:
            $ref: "#/components/schemas/LabelInfo"
        assignees:
          type: array
          items:
            $ref: "#/components/schemas/UserInfo"
        repository:
          $ref: "#/components/schemas/RepositoryInfo"
        additions:
          type: integer
          format: int32
        deletions:
          type: integer
          format: int32
        mergedAt:
          type: string
          format: date-time
        closedAt:
          type: string
          format: date-time
        htmlUrl:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Message:
      required:
      - content
      - id
      - sender
      - sentAt
      - sessionId
      type: object
      properties:
        id:
          type: integer
          format: int64
        sentAt:
          type: string
          format: date-time
        sender:
          type: string
          enum:
          - SYSTEM
          - USER
        content:
          type: string
        sessionId:
          type: integer
          format: int64
    UserProfile:
      required:
      - contributedRepositories
      - firstContribution
      - userInfo
      type: object
      properties:
        userInfo:
          $ref: "#/components/schemas/UserInfo"
        firstContribution:
          type: string
          format: date-time
        contributedRepositories:
          type: array
          items:
            $ref: "#/components/schemas/RepositoryInfo"
        reviewActivity:
          type: array
          items:
            $ref: "#/components/schemas/PullRequestReviewInfo"
        openPullRequests:
          type: array
          items:
            $ref: "#/components/schemas/PullRequestInfo"
    RepositoryInfo:
      required:
      - htmlUrl
      - id
      - name
      - nameWithOwner
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        nameWithOwner:
          type: string
        description:
          type: string
        htmlUrl:
          type: string
    UserTeams:
      required:
      - id
      - login
      - name
      - teams
      - url
      type: object
      properties:
        id:
          type: integer
          format: int64
        login:
          type: string
        name:
          type: string
        url:
          type: string
        teams:
          uniqueItems: true
          type: array
          items:
            $ref: "#/components/schemas/TeamInfo"
    PullRequestBaseInfo:
      required:
      - htmlUrl
      - id
      - isDraft
      - isMerged
      - number
      - state
      - title
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: integer
          format: int32
        title:
          type: string
        state:
          type: string
          enum:
          - OPEN
          - CLOSED
        isDraft:
          type: boolean
        isMerged:
          type: boolean
        repository:
          $ref: "#/components/schemas/RepositoryInfo"
        htmlUrl:
          type: string
    UserInfo:
      required:
      - avatarUrl
      - htmlUrl
      - id
      - login
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        login:
          type: string
        email:
          type: string
        avatarUrl:
          type: string
        name:
          type: string
        htmlUrl:
          type: string
    TeamInfo:
      required:
      - color
      - id
      - labels
      - name
      - repositories
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        color:
          type: string
        repositories:
          type: array
          items:
            $ref: "#/components/schemas/RepositoryInfo"
        labels:
          type: array
          items:
            $ref: "#/components/schemas/LabelInfo"
    LabelInfo:
      required:
      - color
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        color:
          type: string
        repository:
          $ref: "#/components/schemas/RepositoryInfo"
    PullRequestReviewInfo:
      required:
      - codeComments
      - htmlUrl
      - id
      - isDismissed
      - score
      - state
      type: object
      properties:
        id:
          type: integer
          format: int64
        isDismissed:
          type: boolean
        state:
          type: string
          enum:
          - COMMENTED
          - APPROVED
          - CHANGES_REQUESTED
          - UNKNOWN
        codeComments:
          type: integer
          format: int32
        author:
          $ref: "#/components/schemas/UserInfo"
        pullRequest:
          $ref: "#/components/schemas/PullRequestBaseInfo"
        htmlUrl:
          type: string
        score:
          type: integer
          format: int32
        submittedAt:
          type: string
          format: date-time
    MetaData:
      required:
      - scheduledDay
      - scheduledTime
      - teams
      type: object
      properties:
        teams:
          type: array
          items:
            $ref: "#/components/schemas/TeamInfo"
        scheduledDay:
          type: string
        scheduledTime:
          type: string
    LeaderboardEntry:
      required:
      - numberOfApprovals
      - numberOfChangeRequests
      - numberOfCodeComments
      - numberOfComments
      - numberOfReviewedPRs
      - numberOfUnknowns
      - rank
      - reviewedPullRequests
      - score
      - user
      type: object
      properties:
        rank:
          type: integer
          format: int32
        score:
          type: integer
          format: int32
        user:
          $ref: "#/components/schemas/UserInfo"
        reviewedPullRequests:
          type: array
          items:
            $ref: "#/components/schemas/PullRequestInfo"
        numberOfReviewedPRs:
          type: integer
          format: int32
        numberOfApprovals:
          type: integer
          format: int32
        numberOfChangeRequests:
          type: integer
          format: int32
        numberOfComments:
          type: integer
          format: int32
        numberOfUnknowns:
          type: integer
          format: int32
        numberOfCodeComments:
          type: integer
          format: int32
    Session:
      required:
      - createdAt
      - id
      - messages
      - userLogin
      type: object
      properties:
        id:
          type: integer
          format: int64
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
        userLogin:
          type: string
        createdAt:
          type: string
          format: date-time
