/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as WWorkspaceSlugLoginRouteImport } from './routes/w/$workspaceSlug/login'
import { Route as AuthenticatedMentorMentor_accessRouteImport } from './routes/_authenticated/mentor/_mentor_access'
import { Route as AuthenticatedAdminWorkspacesRouteImport } from './routes/_authenticated/admin.workspaces'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin.usage'
import { Route as AuthenticatedAdminLoginProvidersRouteImport } from './routes/_authenticated/admin.login-providers'
import { Route as AuthenticatedAdminLlmRouteImport } from './routes/_authenticated/admin.llm'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedWorkspacesNewIndexRouteImport } from './routes/_authenticated/workspaces/new/index'
import { Route as AuthenticatedWWorkspaceSlugIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/index'
import { Route as AuthenticatedWorkspacesNewGitlabRouteImport } from './routes/_authenticated/workspaces/new/gitlab'
import { Route as AuthenticatedWorkspacesNewGithubRouteImport } from './routes/_authenticated/workspaces/new/github'
import { Route as AuthenticatedWWorkspaceSlugMentorRouteImport } from './routes/_authenticated/w/$workspaceSlug/mentor'
import { Route as AuthenticatedWWorkspaceSlugAchievementsRouteImport } from './routes/_authenticated/w/$workspaceSlug/achievements'
import { Route as AuthenticatedWWorkspaceSlugAdminRouteRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/route'
import { Route as AuthenticatedWWorkspaceSlugTeamsIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/teams/index'
import { Route as AuthenticatedWWorkspaceSlugMentorIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/mentor/index'
import { Route as AuthenticatedWWorkspaceSlugMentorThreadIdRouteImport } from './routes/_authenticated/w/$workspaceSlug/mentor/$threadId'
import { Route as AuthenticatedWWorkspaceSlugAdminUsageRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/usage'
import { Route as AuthenticatedWWorkspaceSlugAdminTeamsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/teams'
import { Route as AuthenticatedWWorkspaceSlugAdminSettingsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/settings'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices'
import { Route as AuthenticatedWWorkspaceSlugAdminModelsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/models'
import { Route as AuthenticatedWWorkspaceSlugAdminMembersRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/members'
import { Route as AuthenticatedWWorkspaceSlugAdminIntegrationsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/integrations'
import { Route as AuthenticatedWWorkspaceSlugAdminAuditRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/audit'
import { Route as AuthenticatedWWorkspaceSlugAdminAchievementsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/achievements'
import { Route as AuthenticatedWWorkspaceSlugAdminAchievementDesignerRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/achievement-designer'
import { Route as AuthenticatedWWorkspaceSlugUserUsernameIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/user/$username/index'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/index'
import { Route as AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/integrations/index'
import { Route as AuthenticatedWWorkspaceSlugUserUsernameAchievementsRouteImport } from './routes/_authenticated/w/$workspaceSlug/user/$username/achievements'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesSettingsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/settings'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesRunsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/runs'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesNewRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/new'
import { Route as AuthenticatedWWorkspaceSlugAdminPracticesPracticeSlugRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/practices/$practiceSlug'
import { Route as AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/integrations/slack'
import { Route as AuthenticatedWWorkspaceSlugAdminIntegrationsScmRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/integrations/scm'
import { Route as AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/integrations/outline'
import { Route as AuthenticatedWWorkspaceSlugAdminAiPracticeDetectionRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/ai/practice-detection'
import { Route as AuthenticatedWWorkspaceSlugAdminAiAgentsRouteImport } from './routes/_authenticated/w/$workspaceSlug/admin/ai/agents'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const WWorkspaceSlugLoginRoute = WWorkspaceSlugLoginRouteImport.update({
  id: '/w/$workspaceSlug/login',
  path: '/w/$workspaceSlug/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMentorMentor_accessRoute =
  AuthenticatedMentorMentor_accessRouteImport.update({
    id: '/mentor/_mentor_access',
    path: '/mentor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkspacesRoute =
  AuthenticatedAdminWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLoginProvidersRoute =
  AuthenticatedAdminLoginProvidersRouteImport.update({
    id: '/login-providers',
    path: '/login-providers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLlmRoute = AuthenticatedAdminLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedWorkspacesNewIndexRoute =
  AuthenticatedWorkspacesNewIndexRouteImport.update({
    id: '/workspaces/new/',
    path: '/workspaces/new/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWWorkspaceSlugIndexRoute =
  AuthenticatedWWorkspaceSlugIndexRouteImport.update({
    id: '/w/$workspaceSlug/',
    path: '/w/$workspaceSlug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesNewGitlabRoute =
  AuthenticatedWorkspacesNewGitlabRouteImport.update({
    id: '/workspaces/new/gitlab',
    path: '/workspaces/new/gitlab',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesNewGithubRoute =
  AuthenticatedWorkspacesNewGithubRouteImport.update({
    id: '/workspaces/new/github',
    path: '/workspaces/new/github',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWWorkspaceSlugMentorRoute =
  AuthenticatedWWorkspaceSlugMentorRouteImport.update({
    id: '/w/$workspaceSlug/mentor',
    path: '/w/$workspaceSlug/mentor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAchievementsRoute =
  AuthenticatedWWorkspaceSlugAchievementsRouteImport.update({
    id: '/w/$workspaceSlug/achievements',
    path: '/w/$workspaceSlug/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminRouteRoute =
  AuthenticatedWWorkspaceSlugAdminRouteRouteImport.update({
    id: '/w/$workspaceSlug/admin',
    path: '/w/$workspaceSlug/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWWorkspaceSlugTeamsIndexRoute =
  AuthenticatedWWorkspaceSlugTeamsIndexRouteImport.update({
    id: '/w/$workspaceSlug/teams/',
    path: '/w/$workspaceSlug/teams/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWWorkspaceSlugMentorIndexRoute =
  AuthenticatedWWorkspaceSlugMentorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugMentorRoute,
  } as any)
const AuthenticatedWWorkspaceSlugMentorThreadIdRoute =
  AuthenticatedWWorkspaceSlugMentorThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedWWorkspaceSlugMentorRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminUsageRoute =
  AuthenticatedWWorkspaceSlugAdminUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminTeamsRoute =
  AuthenticatedWWorkspaceSlugAdminTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminSettingsRoute =
  AuthenticatedWWorkspaceSlugAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesRouteImport.update({
    id: '/practices',
    path: '/practices',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminModelsRoute =
  AuthenticatedWWorkspaceSlugAdminModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminMembersRoute =
  AuthenticatedWWorkspaceSlugAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminIntegrationsRoute =
  AuthenticatedWWorkspaceSlugAdminIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminAuditRoute =
  AuthenticatedWWorkspaceSlugAdminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminAchievementsRoute =
  AuthenticatedWWorkspaceSlugAdminAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminAchievementDesignerRoute =
  AuthenticatedWWorkspaceSlugAdminAchievementDesignerRouteImport.update({
    id: '/achievement-designer',
    path: '/achievement-designer',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugUserUsernameIndexRoute =
  AuthenticatedWWorkspaceSlugUserUsernameIndexRouteImport.update({
    id: '/w/$workspaceSlug/user/$username/',
    path: '/w/$workspaceSlug/user/$username/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute =
  AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminIntegrationsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugUserUsernameAchievementsRoute =
  AuthenticatedWWorkspaceSlugUserUsernameAchievementsRouteImport.update({
    id: '/w/$workspaceSlug/user/$username/achievements',
    path: '/w/$workspaceSlug/user/$username/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesSettingsRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesRunsRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesRunsRouteImport.update({
    id: '/runs',
    path: '/runs',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesNewRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminPracticesPracticeSlugRoute =
  AuthenticatedWWorkspaceSlugAdminPracticesPracticeSlugRouteImport.update({
    id: '/$practiceSlug',
    path: '/$practiceSlug',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminPracticesRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute =
  AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRouteImport.update({
    id: '/slack',
    path: '/slack',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminIntegrationsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute =
  AuthenticatedWWorkspaceSlugAdminIntegrationsScmRouteImport.update({
    id: '/scm',
    path: '/scm',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminIntegrationsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute =
  AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRouteImport.update({
    id: '/outline',
    path: '/outline',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminIntegrationsRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminAiPracticeDetectionRoute =
  AuthenticatedWWorkspaceSlugAdminAiPracticeDetectionRouteImport.update({
    id: '/ai/practice-detection',
    path: '/ai/practice-detection',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)
const AuthenticatedWWorkspaceSlugAdminAiAgentsRoute =
  AuthenticatedWWorkspaceSlugAdminAiAgentsRouteImport.update({
    id: '/ai/agents',
    path: '/ai/agents',
    getParentRoute: () => AuthenticatedWWorkspaceSlugAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/imprint': typeof ImprintRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/llm': typeof AuthenticatedAdminLlmRoute
  '/admin/login-providers': typeof AuthenticatedAdminLoginProvidersRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/mentor': typeof AuthenticatedMentorMentor_accessRoute
  '/w/$workspaceSlug/login': typeof WWorkspaceSlugLoginRoute
  '/w/$workspaceSlug/admin': typeof AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren
  '/w/$workspaceSlug/achievements': typeof AuthenticatedWWorkspaceSlugAchievementsRoute
  '/w/$workspaceSlug/mentor': typeof AuthenticatedWWorkspaceSlugMentorRouteWithChildren
  '/workspaces/new/github': typeof AuthenticatedWorkspacesNewGithubRoute
  '/workspaces/new/gitlab': typeof AuthenticatedWorkspacesNewGitlabRoute
  '/w/$workspaceSlug/': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/workspaces/new/': typeof AuthenticatedWorkspacesNewIndexRoute
  '/w/$workspaceSlug/admin/achievement-designer': typeof AuthenticatedWWorkspaceSlugAdminAchievementDesignerRoute
  '/w/$workspaceSlug/admin/achievements': typeof AuthenticatedWWorkspaceSlugAdminAchievementsRoute
  '/w/$workspaceSlug/admin/audit': typeof AuthenticatedWWorkspaceSlugAdminAuditRoute
  '/w/$workspaceSlug/admin/integrations': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRouteWithChildren
  '/w/$workspaceSlug/admin/members': typeof AuthenticatedWWorkspaceSlugAdminMembersRoute
  '/w/$workspaceSlug/admin/models': typeof AuthenticatedWWorkspaceSlugAdminModelsRoute
  '/w/$workspaceSlug/admin/practices': typeof AuthenticatedWWorkspaceSlugAdminPracticesRouteWithChildren
  '/w/$workspaceSlug/admin/settings': typeof AuthenticatedWWorkspaceSlugAdminSettingsRoute
  '/w/$workspaceSlug/admin/teams': typeof AuthenticatedWWorkspaceSlugAdminTeamsRoute
  '/w/$workspaceSlug/admin/usage': typeof AuthenticatedWWorkspaceSlugAdminUsageRoute
  '/w/$workspaceSlug/mentor/$threadId': typeof AuthenticatedWWorkspaceSlugMentorThreadIdRoute
  '/w/$workspaceSlug/mentor/': typeof AuthenticatedWWorkspaceSlugMentorIndexRoute
  '/w/$workspaceSlug/teams/': typeof AuthenticatedWWorkspaceSlugTeamsIndexRoute
  '/w/$workspaceSlug/admin/ai/agents': typeof AuthenticatedWWorkspaceSlugAdminAiAgentsRoute
  '/w/$workspaceSlug/admin/ai/practice-detection': typeof AuthenticatedWWorkspaceSlugAdminAiPracticeDetectionRoute
  '/w/$workspaceSlug/admin/integrations/outline': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute
  '/w/$workspaceSlug/admin/integrations/scm': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute
  '/w/$workspaceSlug/admin/integrations/slack': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute
  '/w/$workspaceSlug/admin/practices/$practiceSlug': typeof AuthenticatedWWorkspaceSlugAdminPracticesPracticeSlugRoute
  '/w/$workspaceSlug/admin/practices/new': typeof AuthenticatedWWorkspaceSlugAdminPracticesNewRoute
  '/w/$workspaceSlug/admin/practices/runs': typeof AuthenticatedWWorkspaceSlugAdminPracticesRunsRoute
  '/w/$workspaceSlug/admin/practices/settings': typeof AuthenticatedWWorkspaceSlugAdminPracticesSettingsRoute
  '/w/$workspaceSlug/user/$username/achievements': typeof AuthenticatedWWorkspaceSlugUserUsernameAchievementsRoute
  '/w/$workspaceSlug/admin/integrations/': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute
  '/w/$workspaceSlug/admin/practices/': typeof AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute
  '/w/$workspaceSlug/user/$username/': typeof AuthenticatedWWorkspaceSlugUserUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/imprint': typeof ImprintRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/llm': typeof AuthenticatedAdminLlmRoute
  '/admin/login-providers': typeof AuthenticatedAdminLoginProvidersRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/mentor': typeof AuthenticatedMentorMentor_accessRoute
  '/w/$workspaceSlug/login': typeof WWorkspaceSlugLoginRoute
  '/w/$workspaceSlug/admin': typeof AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren
  '/w/$workspaceSlug/achievements': typeof AuthenticatedWWorkspaceSlugAchievementsRoute
  '/workspaces/new/github': typeof AuthenticatedWorkspacesNewGithubRoute
  '/workspaces/new/gitlab': typeof AuthenticatedWorkspacesNewGitlabRoute
  '/w/$workspaceSlug': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/workspaces/new': typeof AuthenticatedWorkspacesNewIndexRoute
  '/w/$workspaceSlug/admin/achievement-designer': typeof AuthenticatedWWorkspaceSlugAdminAchievementDesignerRoute
  '/w/$workspaceSlug/admin/achievements': typeof AuthenticatedWWorkspaceSlugAdminAchievementsRoute
  '/w/$workspaceSlug/admin/audit': typeof AuthenticatedWWorkspaceSlugAdminAuditRoute
  '/w/$workspaceSlug/admin/members': typeof AuthenticatedWWorkspaceSlugAdminMembersRoute
  '/w/$workspaceSlug/admin/models': typeof AuthenticatedWWorkspaceSlugAdminModelsRoute
  '/w/$workspaceSlug/admin/settings': typeof AuthenticatedWWorkspaceSlugAdminSettingsRoute
  '/w/$workspaceSlug/admin/teams': typeof AuthenticatedWWorkspaceSlugAdminTeamsRoute
  '/w/$workspaceSlug/admin/usage': typeof AuthenticatedWWorkspaceSlugAdminUsageRoute
  '/w/$workspaceSlug/mentor/$threadId': typeof AuthenticatedWWorkspaceSlugMentorThreadIdRoute
  '/w/$workspaceSlug/mentor': typeof AuthenticatedWWorkspaceSlugMentorIndexRoute
  '/w/$workspaceSlug/teams': typeof AuthenticatedWWorkspaceSlugTeamsIndexRoute
  '/w/$workspaceSlug/admin/ai/agents': typeof AuthenticatedWWorkspaceSlugAdminAiAgentsRoute
  '/w/$workspaceSlug/admin/ai/practice-detection': typeof AuthenticatedWWorkspaceSlugAdminAiPracticeDetectionRoute
  '/w/$workspaceSlug/admin/integrations/outline': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute
  '/w/$workspaceSlug/admin/integrations/scm': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute
  '/w/$workspaceSlug/admin/integrations/slack': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute
  '/w/$workspaceSlug/admin/practices/$practiceSlug': typeof AuthenticatedWWorkspaceSlugAdminPracticesPracticeSlugRoute
  '/w/$workspaceSlug/admin/practices/new': typeof AuthenticatedWWorkspaceSlugAdminPracticesNewRoute
  '/w/$workspaceSlug/admin/practices/runs': typeof AuthenticatedWWorkspaceSlugAdminPracticesRunsRoute
  '/w/$workspaceSlug/admin/practices/settings': typeof AuthenticatedWWorkspaceSlugAdminPracticesSettingsRoute
  '/w/$workspaceSlug/user/$username/achievements': typeof AuthenticatedWWorkspaceSlugUserUsernameAchievementsRoute
  '/w/$workspaceSlug/admin/integrations': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute
  '/w/$workspaceSlug/admin/practices': typeof AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute
  '/w/$workspaceSlug/user/$username': typeof AuthenticatedWWorkspaceSlugUserUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/imprint': typeof ImprintRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/error': typeof AuthErrorRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/llm': typeof AuthenticatedAdminLlmRoute
  '/_authenticated/admin/login-providers': typeof AuthenticatedAdminLoginProvidersRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/_authenticated/mentor/_mentor_access': typeof AuthenticatedMentorMentor_accessRoute
  '/w/$workspaceSlug/login': typeof WWorkspaceSlugLoginRoute
  '/_authenticated/w/$workspaceSlug/admin': typeof AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren
  '/_authenticated/w/$workspaceSlug/achievements': typeof AuthenticatedWWorkspaceSlugAchievementsRoute
  '/_authenticated/w/$workspaceSlug/mentor': typeof AuthenticatedWWorkspaceSlugMentorRouteWithChildren
  '/_authenticated/workspaces/new/github': typeof AuthenticatedWorkspacesNewGithubRoute
  '/_authenticated/workspaces/new/gitlab': typeof AuthenticatedWorkspacesNewGitlabRoute
  '/_authenticated/w/$workspaceSlug/': typeof AuthenticatedWWorkspaceSlugIndexRoute
  '/_authenticated/workspaces/new/': typeof AuthenticatedWorkspacesNewIndexRoute
  '/_authenticated/w/$workspaceSlug/admin/achievement-designer': typeof AuthenticatedWWorkspaceSlugAdminAchievementDesignerRoute
  '/_authenticated/w/$workspaceSlug/admin/achievements': typeof AuthenticatedWWorkspaceSlugAdminAchievementsRoute
  '/_authenticated/w/$workspaceSlug/admin/audit': typeof AuthenticatedWWorkspaceSlugAdminAuditRoute
  '/_authenticated/w/$workspaceSlug/admin/integrations': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRouteWithChildren
  '/_authenticated/w/$workspaceSlug/admin/members': typeof AuthenticatedWWorkspaceSlugAdminMembersRoute
  '/_authenticated/w/$workspaceSlug/admin/models': typeof AuthenticatedWWorkspaceSlugAdminModelsRoute
  '/_authenticated/w/$workspaceSlug/admin/practices': typeof AuthenticatedWWorkspaceSlugAdminPracticesRouteWithChildren
  '/_authenticated/w/$workspaceSlug/admin/settings': typeof AuthenticatedWWorkspaceSlugAdminSettingsRoute
  '/_authenticated/w/$workspaceSlug/admin/teams': typeof AuthenticatedWWorkspaceSlugAdminTeamsRoute
  '/_authenticated/w/$workspaceSlug/admin/usage': typeof AuthenticatedWWorkspaceSlugAdminUsageRoute
  '/_authenticated/w/$workspaceSlug/mentor/$threadId': typeof AuthenticatedWWorkspaceSlugMentorThreadIdRoute
  '/_authenticated/w/$workspaceSlug/mentor/': typeof AuthenticatedWWorkspaceSlugMentorIndexRoute
  '/_authenticated/w/$workspaceSlug/teams/': typeof AuthenticatedWWorkspaceSlugTeamsIndexRoute
  '/_authenticated/w/$workspaceSlug/admin/ai/agents': typeof AuthenticatedWWorkspaceSlugAdminAiAgentsRoute
  '/_authenticated/w/$workspaceSlug/admin/ai/practice-detection': typeof AuthenticatedWWorkspaceSlugAdminAiPracticeDetectionRoute
  '/_authenticated/w/$workspaceSlug/admin/integrations/outline': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute
  '/_authenticated/w/$workspaceSlug/admin/integrations/scm': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute
  '/_authenticated/w/$workspaceSlug/admin/integrations/slack': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/$practiceSlug': typeof AuthenticatedWWorkspaceSlugAdminPracticesPracticeSlugRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/new': typeof AuthenticatedWWorkspaceSlugAdminPracticesNewRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/runs': typeof AuthenticatedWWorkspaceSlugAdminPracticesRunsRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/settings': typeof AuthenticatedWWorkspaceSlugAdminPracticesSettingsRoute
  '/_authenticated/w/$workspaceSlug/user/$username/achievements': typeof AuthenticatedWWorkspaceSlugUserUsernameAchievementsRoute
  '/_authenticated/w/$workspaceSlug/admin/integrations/': typeof AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute
  '/_authenticated/w/$workspaceSlug/admin/practices/': typeof AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute
  '/_authenticated/w/$workspaceSlug/user/$username/': typeof AuthenticatedWWorkspaceSlugUserUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/imprint'
    | '/landing'
    | '/login'
    | '/privacy'
    | '/admin'
    | '/integrations'
    | '/settings'
    | '/auth/callback'
    | '/auth/error'
    | '/admin/audit'
    | '/admin/llm'
    | '/admin/login-providers'
    | '/admin/usage'
    | '/admin/users'
    | '/admin/workspaces'
    | '/mentor'
    | '/w/$workspaceSlug/login'
    | '/w/$workspaceSlug/admin'
    | '/w/$workspaceSlug/achievements'
    | '/w/$workspaceSlug/mentor'
    | '/workspaces/new/github'
    | '/workspaces/new/gitlab'
    | '/w/$workspaceSlug/'
    | '/workspaces/new/'
    | '/w/$workspaceSlug/admin/achievement-designer'
    | '/w/$workspaceSlug/admin/achievements'
    | '/w/$workspaceSlug/admin/audit'
    | '/w/$workspaceSlug/admin/integrations'
    | '/w/$workspaceSlug/admin/members'
    | '/w/$workspaceSlug/admin/models'
    | '/w/$workspaceSlug/admin/practices'
    | '/w/$workspaceSlug/admin/settings'
    | '/w/$workspaceSlug/admin/teams'
    | '/w/$workspaceSlug/admin/usage'
    | '/w/$workspaceSlug/mentor/$threadId'
    | '/w/$workspaceSlug/mentor/'
    | '/w/$workspaceSlug/teams/'
    | '/w/$workspaceSlug/admin/ai/agents'
    | '/w/$workspaceSlug/admin/ai/practice-detection'
    | '/w/$workspaceSlug/admin/integrations/outline'
    | '/w/$workspaceSlug/admin/integrations/scm'
    | '/w/$workspaceSlug/admin/integrations/slack'
    | '/w/$workspaceSlug/admin/practices/$practiceSlug'
    | '/w/$workspaceSlug/admin/practices/new'
    | '/w/$workspaceSlug/admin/practices/runs'
    | '/w/$workspaceSlug/admin/practices/settings'
    | '/w/$workspaceSlug/user/$username/achievements'
    | '/w/$workspaceSlug/admin/integrations/'
    | '/w/$workspaceSlug/admin/practices/'
    | '/w/$workspaceSlug/user/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/imprint'
    | '/landing'
    | '/login'
    | '/privacy'
    | '/admin'
    | '/integrations'
    | '/settings'
    | '/auth/callback'
    | '/auth/error'
    | '/admin/audit'
    | '/admin/llm'
    | '/admin/login-providers'
    | '/admin/usage'
    | '/admin/users'
    | '/admin/workspaces'
    | '/mentor'
    | '/w/$workspaceSlug/login'
    | '/w/$workspaceSlug/admin'
    | '/w/$workspaceSlug/achievements'
    | '/workspaces/new/github'
    | '/workspaces/new/gitlab'
    | '/w/$workspaceSlug'
    | '/workspaces/new'
    | '/w/$workspaceSlug/admin/achievement-designer'
    | '/w/$workspaceSlug/admin/achievements'
    | '/w/$workspaceSlug/admin/audit'
    | '/w/$workspaceSlug/admin/members'
    | '/w/$workspaceSlug/admin/models'
    | '/w/$workspaceSlug/admin/settings'
    | '/w/$workspaceSlug/admin/teams'
    | '/w/$workspaceSlug/admin/usage'
    | '/w/$workspaceSlug/mentor/$threadId'
    | '/w/$workspaceSlug/mentor'
    | '/w/$workspaceSlug/teams'
    | '/w/$workspaceSlug/admin/ai/agents'
    | '/w/$workspaceSlug/admin/ai/practice-detection'
    | '/w/$workspaceSlug/admin/integrations/outline'
    | '/w/$workspaceSlug/admin/integrations/scm'
    | '/w/$workspaceSlug/admin/integrations/slack'
    | '/w/$workspaceSlug/admin/practices/$practiceSlug'
    | '/w/$workspaceSlug/admin/practices/new'
    | '/w/$workspaceSlug/admin/practices/runs'
    | '/w/$workspaceSlug/admin/practices/settings'
    | '/w/$workspaceSlug/user/$username/achievements'
    | '/w/$workspaceSlug/admin/integrations'
    | '/w/$workspaceSlug/admin/practices'
    | '/w/$workspaceSlug/user/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/imprint'
    | '/landing'
    | '/login'
    | '/privacy'
    | '/_authenticated/admin'
    | '/_authenticated/integrations'
    | '/_authenticated/settings'
    | '/auth/callback'
    | '/auth/error'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/llm'
    | '/_authenticated/admin/login-providers'
    | '/_authenticated/admin/usage'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/workspaces'
    | '/_authenticated/mentor/_mentor_access'
    | '/w/$workspaceSlug/login'
    | '/_authenticated/w/$workspaceSlug/admin'
    | '/_authenticated/w/$workspaceSlug/achievements'
    | '/_authenticated/w/$workspaceSlug/mentor'
    | '/_authenticated/workspaces/new/github'
    | '/_authenticated/workspaces/new/gitlab'
    | '/_authenticated/w/$workspaceSlug/'
    | '/_authenticated/workspaces/new/'
    | '/_authenticated/w/$workspaceSlug/admin/achievement-designer'
    | '/_authenticated/w/$workspaceSlug/admin/achievements'
    | '/_authenticated/w/$workspaceSlug/admin/audit'
    | '/_authenticated/w/$workspaceSlug/admin/integrations'
    | '/_authenticated/w/$workspaceSlug/admin/members'
    | '/_authenticated/w/$workspaceSlug/admin/models'
    | '/_authenticated/w/$workspaceSlug/admin/practices'
    | '/_authenticated/w/$workspaceSlug/admin/settings'
    | '/_authenticated/w/$workspaceSlug/admin/teams'
    | '/_authenticated/w/$workspaceSlug/admin/usage'
    | '/_authenticated/w/$workspaceSlug/mentor/$threadId'
    | '/_authenticated/w/$workspaceSlug/mentor/'
    | '/_authenticated/w/$workspaceSlug/teams/'
    | '/_authenticated/w/$workspaceSlug/admin/ai/agents'
    | '/_authenticated/w/$workspaceSlug/admin/ai/practice-detection'
    | '/_authenticated/w/$workspaceSlug/admin/integrations/outline'
    | '/_authenticated/w/$workspaceSlug/admin/integrations/scm'
    | '/_authenticated/w/$workspaceSlug/admin/integrations/slack'
    | '/_authenticated/w/$workspaceSlug/admin/practices/$practiceSlug'
    | '/_authenticated/w/$workspaceSlug/admin/practices/new'
    | '/_authenticated/w/$workspaceSlug/admin/practices/runs'
    | '/_authenticated/w/$workspaceSlug/admin/practices/settings'
    | '/_authenticated/w/$workspaceSlug/user/$username/achievements'
    | '/_authenticated/w/$workspaceSlug/admin/integrations/'
    | '/_authenticated/w/$workspaceSlug/admin/practices/'
    | '/_authenticated/w/$workspaceSlug/user/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ImprintRoute: typeof ImprintRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthErrorRoute: typeof AuthErrorRoute
  WWorkspaceSlugLoginRoute: typeof WWorkspaceSlugLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/w/$workspaceSlug/login': {
      id: '/w/$workspaceSlug/login'
      path: '/w/$workspaceSlug/login'
      fullPath: '/w/$workspaceSlug/login'
      preLoaderRoute: typeof WWorkspaceSlugLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mentor/_mentor_access': {
      id: '/_authenticated/mentor/_mentor_access'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorMentor_accessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workspaces': {
      id: '/_authenticated/admin/workspaces'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AuthenticatedAdminWorkspacesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/login-providers': {
      id: '/_authenticated/admin/login-providers'
      path: '/login-providers'
      fullPath: '/admin/login-providers'
      preLoaderRoute: typeof AuthenticatedAdminLoginProvidersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/llm': {
      id: '/_authenticated/admin/llm'
      path: '/llm'
      fullPath: '/admin/llm'
      preLoaderRoute: typeof AuthenticatedAdminLlmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/workspaces/new/': {
      id: '/_authenticated/workspaces/new/'
      path: '/workspaces/new'
      fullPath: '/workspaces/new/'
      preLoaderRoute: typeof AuthenticatedWorkspacesNewIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$workspaceSlug/': {
      id: '/_authenticated/w/$workspaceSlug/'
      path: '/w/$workspaceSlug'
      fullPath: '/w/$workspaceSlug/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/new/gitlab': {
      id: '/_authenticated/workspaces/new/gitlab'
      path: '/workspaces/new/gitlab'
      fullPath: '/workspaces/new/gitlab'
      preLoaderRoute: typeof AuthenticatedWorkspacesNewGitlabRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/new/github': {
      id: '/_authenticated/workspaces/new/github'
      path: '/workspaces/new/github'
      fullPath: '/workspaces/new/github'
      preLoaderRoute: typeof AuthenticatedWorkspacesNewGithubRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$workspaceSlug/mentor': {
      id: '/_authenticated/w/$workspaceSlug/mentor'
      path: '/w/$workspaceSlug/mentor'
      fullPath: '/w/$workspaceSlug/mentor'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugMentorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$workspaceSlug/achievements': {
      id: '/_authenticated/w/$workspaceSlug/achievements'
      path: '/w/$workspaceSlug/achievements'
      fullPath: '/w/$workspaceSlug/achievements'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$workspaceSlug/admin': {
      id: '/_authenticated/w/$workspaceSlug/admin'
      path: '/w/$workspaceSlug/admin'
      fullPath: '/w/$workspaceSlug/admin'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$workspaceSlug/teams/': {
      id: '/_authenticated/w/$workspaceSlug/teams/'
      path: '/w/$workspaceSlug/teams'
      fullPath: '/w/$workspaceSlug/teams/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$workspaceSlug/mentor/': {
      id: '/_authenticated/w/$workspaceSlug/mentor/'
      path: '/'
      fullPath: '/w/$workspaceSlug/mentor/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugMentorIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugMentorRoute
    }
    '/_authenticated/w/$workspaceSlug/mentor/$threadId': {
      id: '/_authenticated/w/$workspaceSlug/mentor/$threadId'
      path: '/$threadId'
      fullPath: '/w/$workspaceSlug/mentor/$threadId'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugMentorThreadIdRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugMentorRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/usage': {
      id: '/_authenticated/w/$workspaceSlug/admin/usage'
      path: '/usage'
      fullPath: '/w/$workspaceSlug/admin/usage'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminUsageRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/teams': {
      id: '/_authenticated/w/$workspaceSlug/admin/teams'
      path: '/teams'
      fullPath: '/w/$workspaceSlug/admin/teams'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminTeamsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/settings': {
      id: '/_authenticated/w/$workspaceSlug/admin/settings'
      path: '/settings'
      fullPath: '/w/$workspaceSlug/admin/settings'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices'
      path: '/practices'
      fullPath: '/w/$workspaceSlug/admin/practices'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/models': {
      id: '/_authenticated/w/$workspaceSlug/admin/models'
      path: '/models'
      fullPath: '/w/$workspaceSlug/admin/models'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminModelsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/members': {
      id: '/_authenticated/w/$workspaceSlug/admin/members'
      path: '/members'
      fullPath: '/w/$workspaceSlug/admin/members'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminMembersRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/integrations': {
      id: '/_authenticated/w/$workspaceSlug/admin/integrations'
      path: '/integrations'
      fullPath: '/w/$workspaceSlug/admin/integrations'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/audit': {
      id: '/_authenticated/w/$workspaceSlug/admin/audit'
      path: '/audit'
      fullPath: '/w/$workspaceSlug/admin/audit'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminAuditRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/achievements': {
      id: '/_authenticated/w/$workspaceSlug/admin/achievements'
      path: '/achievements'
      fullPath: '/w/$workspaceSlug/admin/achievements'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminAchievementsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/achievement-designer': {
      id: '/_authenticated/w/$workspaceSlug/admin/achievement-designer'
      path: '/achievement-designer'
      fullPath: '/w/$workspaceSlug/admin/achievement-designer'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminAchievementDesignerRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/user/$username/': {
      id: '/_authenticated/w/$workspaceSlug/user/$username/'
      path: '/w/$workspaceSlug/user/$username'
      fullPath: '/w/$workspaceSlug/user/$username/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugUserUsernameIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/'
      path: '/'
      fullPath: '/w/$workspaceSlug/admin/practices/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/integrations/': {
      id: '/_authenticated/w/$workspaceSlug/admin/integrations/'
      path: '/'
      fullPath: '/w/$workspaceSlug/admin/integrations/'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRoute
    }
    '/_authenticated/w/$workspaceSlug/user/$username/achievements': {
      id: '/_authenticated/w/$workspaceSlug/user/$username/achievements'
      path: '/w/$workspaceSlug/user/$username/achievements'
      fullPath: '/w/$workspaceSlug/user/$username/achievements'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugUserUsernameAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/settings': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/settings'
      path: '/settings'
      fullPath: '/w/$workspaceSlug/admin/practices/settings'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesSettingsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/runs': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/runs'
      path: '/runs'
      fullPath: '/w/$workspaceSlug/admin/practices/runs'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRunsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/new': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/new'
      path: '/new'
      fullPath: '/w/$workspaceSlug/admin/practices/new'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesNewRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/practices/$practiceSlug': {
      id: '/_authenticated/w/$workspaceSlug/admin/practices/$practiceSlug'
      path: '/$practiceSlug'
      fullPath: '/w/$workspaceSlug/admin/practices/$practiceSlug'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesPracticeSlugRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/integrations/slack': {
      id: '/_authenticated/w/$workspaceSlug/admin/integrations/slack'
      path: '/slack'
      fullPath: '/w/$workspaceSlug/admin/integrations/slack'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/integrations/scm': {
      id: '/_authenticated/w/$workspaceSlug/admin/integrations/scm'
      path: '/scm'
      fullPath: '/w/$workspaceSlug/admin/integrations/scm'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsScmRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/integrations/outline': {
      id: '/_authenticated/w/$workspaceSlug/admin/integrations/outline'
      path: '/outline'
      fullPath: '/w/$workspaceSlug/admin/integrations/outline'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/ai/practice-detection': {
      id: '/_authenticated/w/$workspaceSlug/admin/ai/practice-detection'
      path: '/ai/practice-detection'
      fullPath: '/w/$workspaceSlug/admin/ai/practice-detection'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminAiPracticeDetectionRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
    '/_authenticated/w/$workspaceSlug/admin/ai/agents': {
      id: '/_authenticated/w/$workspaceSlug/admin/ai/agents'
      path: '/ai/agents'
      fullPath: '/w/$workspaceSlug/admin/ai/agents'
      preLoaderRoute: typeof AuthenticatedWWorkspaceSlugAdminAiAgentsRouteImport
      parentRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminLlmRoute: typeof AuthenticatedAdminLlmRoute
  AuthenticatedAdminLoginProvidersRoute: typeof AuthenticatedAdminLoginProvidersRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWorkspacesRoute: typeof AuthenticatedAdminWorkspacesRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminLlmRoute: AuthenticatedAdminLlmRoute,
  AuthenticatedAdminLoginProvidersRoute: AuthenticatedAdminLoginProvidersRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWorkspacesRoute: AuthenticatedAdminWorkspacesRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedWWorkspaceSlugAdminIntegrationsRouteChildren {
  AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute
  AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute
  AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute
  AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute
}

const AuthenticatedWWorkspaceSlugAdminIntegrationsRouteChildren: AuthenticatedWWorkspaceSlugAdminIntegrationsRouteChildren =
  {
    AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute:
      AuthenticatedWWorkspaceSlugAdminIntegrationsOutlineRoute,
    AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute:
      AuthenticatedWWorkspaceSlugAdminIntegrationsScmRoute,
    AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute:
      AuthenticatedWWorkspaceSlugAdminIntegrationsSlackRoute,
    AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute:
      AuthenticatedWWorkspaceSlugAdminIntegrationsIndexRoute,
  }

const AuthenticatedWWorkspaceSlugAdminIntegrationsRouteWithChildren =
  AuthenticatedWWorkspaceSlugAdminIntegrationsRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugAdminIntegrationsRouteChildren,
  )

interface AuthenticatedWWorkspaceSlugAdminPracticesRouteChildren {
  AuthenticatedWWorkspaceSlugAdminPracticesPracticeSlugRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesPracticeSlugRoute
  AuthenticatedWWorkspaceSlugAdminPracticesNewRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesNewRoute
  AuthenticatedWWorkspaceSlugAdminPracticesRunsRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRunsRoute
  AuthenticatedWWorkspaceSlugAdminPracticesSettingsRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesSettingsRoute
  AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute
}

const AuthenticatedWWorkspaceSlugAdminPracticesRouteChildren: AuthenticatedWWorkspaceSlugAdminPracticesRouteChildren =
  {
    AuthenticatedWWorkspaceSlugAdminPracticesPracticeSlugRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesPracticeSlugRoute,
    AuthenticatedWWorkspaceSlugAdminPracticesNewRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesNewRoute,
    AuthenticatedWWorkspaceSlugAdminPracticesRunsRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesRunsRoute,
    AuthenticatedWWorkspaceSlugAdminPracticesSettingsRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesSettingsRoute,
    AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesIndexRoute,
  }

const AuthenticatedWWorkspaceSlugAdminPracticesRouteWithChildren =
  AuthenticatedWWorkspaceSlugAdminPracticesRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugAdminPracticesRouteChildren,
  )

interface AuthenticatedWWorkspaceSlugAdminRouteRouteChildren {
  AuthenticatedWWorkspaceSlugAdminAchievementDesignerRoute: typeof AuthenticatedWWorkspaceSlugAdminAchievementDesignerRoute
  AuthenticatedWWorkspaceSlugAdminAchievementsRoute: typeof AuthenticatedWWorkspaceSlugAdminAchievementsRoute
  AuthenticatedWWorkspaceSlugAdminAuditRoute: typeof AuthenticatedWWorkspaceSlugAdminAuditRoute
  AuthenticatedWWorkspaceSlugAdminIntegrationsRoute: typeof AuthenticatedWWorkspaceSlugAdminIntegrationsRouteWithChildren
  AuthenticatedWWorkspaceSlugAdminMembersRoute: typeof AuthenticatedWWorkspaceSlugAdminMembersRoute
  AuthenticatedWWorkspaceSlugAdminModelsRoute: typeof AuthenticatedWWorkspaceSlugAdminModelsRoute
  AuthenticatedWWorkspaceSlugAdminPracticesRoute: typeof AuthenticatedWWorkspaceSlugAdminPracticesRouteWithChildren
  AuthenticatedWWorkspaceSlugAdminSettingsRoute: typeof AuthenticatedWWorkspaceSlugAdminSettingsRoute
  AuthenticatedWWorkspaceSlugAdminTeamsRoute: typeof AuthenticatedWWorkspaceSlugAdminTeamsRoute
  AuthenticatedWWorkspaceSlugAdminUsageRoute: typeof AuthenticatedWWorkspaceSlugAdminUsageRoute
  AuthenticatedWWorkspaceSlugAdminAiAgentsRoute: typeof AuthenticatedWWorkspaceSlugAdminAiAgentsRoute
  AuthenticatedWWorkspaceSlugAdminAiPracticeDetectionRoute: typeof AuthenticatedWWorkspaceSlugAdminAiPracticeDetectionRoute
}

const AuthenticatedWWorkspaceSlugAdminRouteRouteChildren: AuthenticatedWWorkspaceSlugAdminRouteRouteChildren =
  {
    AuthenticatedWWorkspaceSlugAdminAchievementDesignerRoute:
      AuthenticatedWWorkspaceSlugAdminAchievementDesignerRoute,
    AuthenticatedWWorkspaceSlugAdminAchievementsRoute:
      AuthenticatedWWorkspaceSlugAdminAchievementsRoute,
    AuthenticatedWWorkspaceSlugAdminAuditRoute:
      AuthenticatedWWorkspaceSlugAdminAuditRoute,
    AuthenticatedWWorkspaceSlugAdminIntegrationsRoute:
      AuthenticatedWWorkspaceSlugAdminIntegrationsRouteWithChildren,
    AuthenticatedWWorkspaceSlugAdminMembersRoute:
      AuthenticatedWWorkspaceSlugAdminMembersRoute,
    AuthenticatedWWorkspaceSlugAdminModelsRoute:
      AuthenticatedWWorkspaceSlugAdminModelsRoute,
    AuthenticatedWWorkspaceSlugAdminPracticesRoute:
      AuthenticatedWWorkspaceSlugAdminPracticesRouteWithChildren,
    AuthenticatedWWorkspaceSlugAdminSettingsRoute:
      AuthenticatedWWorkspaceSlugAdminSettingsRoute,
    AuthenticatedWWorkspaceSlugAdminTeamsRoute:
      AuthenticatedWWorkspaceSlugAdminTeamsRoute,
    AuthenticatedWWorkspaceSlugAdminUsageRoute:
      AuthenticatedWWorkspaceSlugAdminUsageRoute,
    AuthenticatedWWorkspaceSlugAdminAiAgentsRoute:
      AuthenticatedWWorkspaceSlugAdminAiAgentsRoute,
    AuthenticatedWWorkspaceSlugAdminAiPracticeDetectionRoute:
      AuthenticatedWWorkspaceSlugAdminAiPracticeDetectionRoute,
  }

const AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren =
  AuthenticatedWWorkspaceSlugAdminRouteRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugAdminRouteRouteChildren,
  )

interface AuthenticatedWWorkspaceSlugMentorRouteChildren {
  AuthenticatedWWorkspaceSlugMentorThreadIdRoute: typeof AuthenticatedWWorkspaceSlugMentorThreadIdRoute
  AuthenticatedWWorkspaceSlugMentorIndexRoute: typeof AuthenticatedWWorkspaceSlugMentorIndexRoute
}

const AuthenticatedWWorkspaceSlugMentorRouteChildren: AuthenticatedWWorkspaceSlugMentorRouteChildren =
  {
    AuthenticatedWWorkspaceSlugMentorThreadIdRoute:
      AuthenticatedWWorkspaceSlugMentorThreadIdRoute,
    AuthenticatedWWorkspaceSlugMentorIndexRoute:
      AuthenticatedWWorkspaceSlugMentorIndexRoute,
  }

const AuthenticatedWWorkspaceSlugMentorRouteWithChildren =
  AuthenticatedWWorkspaceSlugMentorRoute._addFileChildren(
    AuthenticatedWWorkspaceSlugMentorRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedMentorMentor_accessRoute: typeof AuthenticatedMentorMentor_accessRoute
  AuthenticatedWWorkspaceSlugAdminRouteRoute: typeof AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren
  AuthenticatedWWorkspaceSlugAchievementsRoute: typeof AuthenticatedWWorkspaceSlugAchievementsRoute
  AuthenticatedWWorkspaceSlugMentorRoute: typeof AuthenticatedWWorkspaceSlugMentorRouteWithChildren
  AuthenticatedWorkspacesNewGithubRoute: typeof AuthenticatedWorkspacesNewGithubRoute
  AuthenticatedWorkspacesNewGitlabRoute: typeof AuthenticatedWorkspacesNewGitlabRoute
  AuthenticatedWWorkspaceSlugIndexRoute: typeof AuthenticatedWWorkspaceSlugIndexRoute
  AuthenticatedWorkspacesNewIndexRoute: typeof AuthenticatedWorkspacesNewIndexRoute
  AuthenticatedWWorkspaceSlugTeamsIndexRoute: typeof AuthenticatedWWorkspaceSlugTeamsIndexRoute
  AuthenticatedWWorkspaceSlugUserUsernameAchievementsRoute: typeof AuthenticatedWWorkspaceSlugUserUsernameAchievementsRoute
  AuthenticatedWWorkspaceSlugUserUsernameIndexRoute: typeof AuthenticatedWWorkspaceSlugUserUsernameIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedMentorMentor_accessRoute: AuthenticatedMentorMentor_accessRoute,
  AuthenticatedWWorkspaceSlugAdminRouteRoute:
    AuthenticatedWWorkspaceSlugAdminRouteRouteWithChildren,
  AuthenticatedWWorkspaceSlugAchievementsRoute:
    AuthenticatedWWorkspaceSlugAchievementsRoute,
  AuthenticatedWWorkspaceSlugMentorRoute:
    AuthenticatedWWorkspaceSlugMentorRouteWithChildren,
  AuthenticatedWorkspacesNewGithubRoute: AuthenticatedWorkspacesNewGithubRoute,
  AuthenticatedWorkspacesNewGitlabRoute: AuthenticatedWorkspacesNewGitlabRoute,
  AuthenticatedWWorkspaceSlugIndexRoute: AuthenticatedWWorkspaceSlugIndexRoute,
  AuthenticatedWorkspacesNewIndexRoute: AuthenticatedWorkspacesNewIndexRoute,
  AuthenticatedWWorkspaceSlugTeamsIndexRoute:
    AuthenticatedWWorkspaceSlugTeamsIndexRoute,
  AuthenticatedWWorkspaceSlugUserUsernameAchievementsRoute:
    AuthenticatedWWorkspaceSlugUserUsernameAchievementsRoute,
  AuthenticatedWWorkspaceSlugUserUsernameIndexRoute:
    AuthenticatedWWorkspaceSlugUserUsernameIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ImprintRoute: ImprintRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthErrorRoute: AuthErrorRoute,
  WWorkspaceSlugLoginRoute: WWorkspaceSlugLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
