// This file is auto-generated by @hey-api/openapi-ts

import type { AddLabelToTeamResponse, AssignRoleResponse, CreateDocumentResponse, CreateWorkspaceResponse, DeleteDocumentVersionsAfterResponse, GetAllAchievementDefinitionsResponse, GetAllTeamsResponse, GetBadPracticesForPullRequestResponse, GetBadPracticesForUserResponse, GetCurrentUserMembershipResponse, GetDocumentResponse, GetGroupedThreadsResponse, GetLabelFiltersResponse, GetLeaderboardResponse, GetMemberResponse, GetThreadResponse, GetUserAchievementsResponse, GetUserProfileResponse, GetVersionResponse, GetWorkspaceResponse, ListDocumentsResponse, ListMembersResponse, ListVersionsResponse, ListWorkspacesResponse, RemoveLabelFromTeamResponse, RenameSlugResponse, UpdateDocumentResponse, UpdateNotificationsResponse, UpdatePublicVisibilityResponse, UpdateScheduleResponse, UpdateSlackCredentialsResponse, UpdateStatusResponse, UpdateTokenResponse, VoteMessageResponse } from './types.gen';

const workspaceListItemSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const listWorkspacesResponseTransformer = async (data: any): Promise<ListWorkspacesResponse> => {
    data = data.map((item: any) => workspaceListItemSchemaResponseTransformer(item));
    return data;
};

const workspaceSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    if (data.installationLinkedAt) {
        data.installationLinkedAt = new Date(data.installationLinkedAt);
    }
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const createWorkspaceResponseTransformer = async (data: any): Promise<CreateWorkspaceResponse> => {
    data = workspaceSchemaResponseTransformer(data);
    return data;
};

export const getWorkspaceResponseTransformer = async (data: any): Promise<GetWorkspaceResponse> => {
    data = workspaceSchemaResponseTransformer(data);
    return data;
};

const repositoryInfoSchemaResponseTransformer = (data: any) => {
    if (data.labels) {
        data.labels = data.labels.map((item: any) => labelInfoSchemaResponseTransformer(item));
    }
    return data;
};

const labelInfoSchemaResponseTransformer = (data: any) => {
    if (data.repository) {
        data.repository = repositoryInfoSchemaResponseTransformer(data.repository);
    }
    return data;
};

const pullRequestInfoSchemaResponseTransformer = (data: any) => {
    if (data.closedAt) {
        data.closedAt = new Date(data.closedAt);
    }
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    if (data.labels) {
        data.labels = data.labels.map((item: any) => labelInfoSchemaResponseTransformer(item));
    }
    if (data.mergedAt) {
        data.mergedAt = new Date(data.mergedAt);
    }
    if (data.repository) {
        data.repository = repositoryInfoSchemaResponseTransformer(data.repository);
    }
    if (data.updatedAt) {
        data.updatedAt = new Date(data.updatedAt);
    }
    return data;
};

const teamInfoSchemaResponseTransformer = (data: any) => {
    data.labels = data.labels.map((item: any) => labelInfoSchemaResponseTransformer(item));
    data.repositories = data.repositories.map((item: any) => repositoryInfoSchemaResponseTransformer(item));
    return data;
};

const leaderboardEntrySchemaResponseTransformer = (data: any) => {
    data.reviewedPullRequests = data.reviewedPullRequests.map((item: any) => pullRequestInfoSchemaResponseTransformer(item));
    if (data.team) {
        data.team = teamInfoSchemaResponseTransformer(data.team);
    }
    return data;
};

export const getLeaderboardResponseTransformer = async (data: any): Promise<GetLeaderboardResponse> => {
    data = data.map((item: any) => leaderboardEntrySchemaResponseTransformer(item));
    return data;
};

const workspaceMembershipSchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    return data;
};

export const listMembersResponseTransformer = async (data: any): Promise<ListMembersResponse> => {
    data = data.map((item: any) => workspaceMembershipSchemaResponseTransformer(item));
    return data;
};

export const assignRoleResponseTransformer = async (data: any): Promise<AssignRoleResponse> => {
    data = workspaceMembershipSchemaResponseTransformer(data);
    return data;
};

export const getCurrentUserMembershipResponseTransformer = async (data: any): Promise<GetCurrentUserMembershipResponse> => {
    data = workspaceMembershipSchemaResponseTransformer(data);
    return data;
};

export const getMemberResponseTransformer = async (data: any): Promise<GetMemberResponse> => {
    data = workspaceMembershipSchemaResponseTransformer(data);
    return data;
};

const documentSummarySchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const listDocumentsResponseTransformer = async (data: any): Promise<ListDocumentsResponse> => {
    data = data.map((item: any) => documentSummarySchemaResponseTransformer(item));
    return data;
};

const documentSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const createDocumentResponseTransformer = async (data: any): Promise<CreateDocumentResponse> => {
    data = documentSchemaResponseTransformer(data);
    return data;
};

export const getDocumentResponseTransformer = async (data: any): Promise<GetDocumentResponse> => {
    data = documentSchemaResponseTransformer(data);
    return data;
};

export const updateDocumentResponseTransformer = async (data: any): Promise<UpdateDocumentResponse> => {
    data = documentSchemaResponseTransformer(data);
    return data;
};

export const deleteDocumentVersionsAfterResponseTransformer = async (data: any): Promise<DeleteDocumentVersionsAfterResponse> => {
    data = data.map((item: any) => documentSchemaResponseTransformer(item));
    return data;
};

export const listVersionsResponseTransformer = async (data: any): Promise<ListVersionsResponse> => {
    data = data.map((item: any) => documentSchemaResponseTransformer(item));
    return data;
};

export const getVersionResponseTransformer = async (data: any): Promise<GetVersionResponse> => {
    data = documentSchemaResponseTransformer(data);
    return data;
};

const chatMessageVoteSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const voteMessageResponseTransformer = async (data: any): Promise<VoteMessageResponse> => {
    data = chatMessageVoteSchemaResponseTransformer(data);
    return data;
};

const chatThreadSummarySchemaResponseTransformer = (data: any) => {
    if (data.createdAt) {
        data.createdAt = new Date(data.createdAt);
    }
    return data;
};

const chatThreadGroupSchemaResponseTransformer = (data: any) => {
    data.threads = data.threads.map((item: any) => chatThreadSummarySchemaResponseTransformer(item));
    return data;
};

export const getGroupedThreadsResponseTransformer = async (data: any): Promise<GetGroupedThreadsResponse> => {
    data = data.map((item: any) => chatThreadGroupSchemaResponseTransformer(item));
    return data;
};

const threadDetailSchemaResponseTransformer = (data: any) => {
    data.messages = data.messages.map((item: any) => {
        if (item.createdAt) {
            item.createdAt = new Date(item.createdAt);
        }
        return item;
    });
    return data;
};

export const getThreadResponseTransformer = async (data: any): Promise<GetThreadResponse> => {
    data = threadDetailSchemaResponseTransformer(data);
    return data;
};

export const updateNotificationsResponseTransformer = async (data: any): Promise<UpdateNotificationsResponse> => {
    data = workspaceSchemaResponseTransformer(data);
    return data;
};

const pullRequestWithBadPracticesSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.labels = data.labels.map((item: any) => labelInfoSchemaResponseTransformer(item));
    data.repository = repositoryInfoSchemaResponseTransformer(data.repository);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const getBadPracticesForPullRequestResponseTransformer = async (data: any): Promise<GetBadPracticesForPullRequestResponse> => {
    data = pullRequestWithBadPracticesSchemaResponseTransformer(data);
    return data;
};

const userPracticesSchemaResponseTransformer = (data: any) => {
    if (data.pullRequests) {
        data.pullRequests = data.pullRequests.map((item: any) => pullRequestWithBadPracticesSchemaResponseTransformer(item));
    }
    return data;
};

export const getBadPracticesForUserResponseTransformer = async (data: any): Promise<GetBadPracticesForUserResponse> => {
    data = userPracticesSchemaResponseTransformer(data);
    return data;
};

const pullRequestBaseInfoSchemaResponseTransformer = (data: any) => {
    if (data.repository) {
        data.repository = repositoryInfoSchemaResponseTransformer(data.repository);
    }
    return data;
};

const profileReviewActivitySchemaResponseTransformer = (data: any) => {
    if (data.pullRequest) {
        data.pullRequest = pullRequestBaseInfoSchemaResponseTransformer(data.pullRequest);
    }
    if (data.submittedAt) {
        data.submittedAt = new Date(data.submittedAt);
    }
    return data;
};

const profileSchemaResponseTransformer = (data: any) => {
    data.contributedRepositories = data.contributedRepositories.map((item: any) => repositoryInfoSchemaResponseTransformer(item));
    if (data.firstContribution) {
        data.firstContribution = new Date(data.firstContribution);
    }
    if (data.openPullRequests) {
        data.openPullRequests = data.openPullRequests.map((item: any) => pullRequestInfoSchemaResponseTransformer(item));
    }
    if (data.reviewActivity) {
        data.reviewActivity = data.reviewActivity.map((item: any) => profileReviewActivitySchemaResponseTransformer(item));
    }
    if (data.reviewedPullRequests) {
        data.reviewedPullRequests = data.reviewedPullRequests.map((item: any) => pullRequestInfoSchemaResponseTransformer(item));
    }
    return data;
};

export const getUserProfileResponseTransformer = async (data: any): Promise<GetUserProfileResponse> => {
    data = profileSchemaResponseTransformer(data);
    return data;
};

export const updatePublicVisibilityResponseTransformer = async (data: any): Promise<UpdatePublicVisibilityResponse> => {
    data = workspaceSchemaResponseTransformer(data);
    return data;
};

export const updateScheduleResponseTransformer = async (data: any): Promise<UpdateScheduleResponse> => {
    data = workspaceSchemaResponseTransformer(data);
    return data;
};

export const updateSlackCredentialsResponseTransformer = async (data: any): Promise<UpdateSlackCredentialsResponse> => {
    data = workspaceSchemaResponseTransformer(data);
    return data;
};

export const renameSlugResponseTransformer = async (data: any): Promise<RenameSlugResponse> => {
    data = workspaceSchemaResponseTransformer(data);
    return data;
};

export const updateStatusResponseTransformer = async (data: any): Promise<UpdateStatusResponse> => {
    data = workspaceSchemaResponseTransformer(data);
    return data;
};

export const getAllTeamsResponseTransformer = async (data: any): Promise<GetAllTeamsResponse> => {
    data = data.map((item: any) => teamInfoSchemaResponseTransformer(item));
    return data;
};

export const removeLabelFromTeamResponseTransformer = async (data: any): Promise<RemoveLabelFromTeamResponse> => {
    data = teamInfoSchemaResponseTransformer(data);
    return data;
};

export const addLabelToTeamResponseTransformer = async (data: any): Promise<AddLabelToTeamResponse> => {
    data = teamInfoSchemaResponseTransformer(data);
    return data;
};

export const getLabelFiltersResponseTransformer = async (data: any): Promise<GetLabelFiltersResponse> => {
    data = data.map((item: any) => labelInfoSchemaResponseTransformer(item));
    return data;
};

export const updateTokenResponseTransformer = async (data: any): Promise<UpdateTokenResponse> => {
    data = workspaceSchemaResponseTransformer(data);
    return data;
};

const achievementSchemaResponseTransformer = (data: any) => {
    data.unlockedAt = new Date(data.unlockedAt);
    return data;
};

export const getUserAchievementsResponseTransformer = async (data: any): Promise<GetUserAchievementsResponse> => {
    data = data.map((item: any) => achievementSchemaResponseTransformer(item));
    return data;
};

export const getAllAchievementDefinitionsResponseTransformer = async (data: any): Promise<GetAllAchievementDefinitionsResponse> => {
    data = data.map((item: any) => achievementSchemaResponseTransformer(item));
    return data;
};
