# GraphQL.vscode-graphql uses this file for schema-aware editing.

projects:
  github:
    schema: "server/generated-clients/src/main/resources/graphql/github/schema.github.graphql"
    documents:
      - "server/generated-clients/src/main/resources/graphql/github/operations/**/*.graphql"
      - "server/generated-clients/src/main/resources/graphql/github/fragments/**/*.graphql"
    include:
      - "server/generated-clients/src/main/resources/graphql/github/**"

    extensions:
      languageService:
        enableHover: true
        enableAutoComplete: true
        enableValidation: true

  gitlab:
    schema: "server/generated-clients/src/main/resources/graphql/gitlab/schema.gitlab.graphql"
    documents: "server/generated-clients/src/main/resources/graphql/gitlab/operations/**/*.graphql"
    include:
      - "server/generated-clients/src/main/resources/graphql/gitlab/**"

    extensions:
      languageService:
        enableHover: true
        enableAutoComplete: true
        enableValidation: true
