services:
  application-server:
    image: hephaestus-application-server
    ports:
      - '8080'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://postgres:5432/hephaestus
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - SECURITY_USER_NAME=${SECURITY_USER_NAME:-admin}
      - SECURITY_USER_PASSWORD=${SECURITY_USER_NAME:-admin_password}
    depends_on:
      - postgres
    networks:
      - app-network
    healthcheck:
      test: "wget -qO- http://localhost:8080/actuator/health || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  intelligence-service:
    build: server/intelligence-service
    ports:
      - "8000"
    environment:
      # Either OPENAI_API_KEY or AZURE_OPENAI_API_KEY must be set
      - OPENAI_API_KEY
      - AZURE_OPENAI_API_KEY
      - AZURE_OPENAI_ENDPOINT
      - AZURE_OPENAI_API_VERSION
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: 'postgres:16'
    environment:
      - POSTGRES_DB=hephaestus
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - '5432'
    networks:
      app-network:
        aliases:
          - postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge`