services:
  application-server:
    image: hephaestus-application-server
    ports:
      - '9000:8080'
    environment:
      - SERVICE_FQDN_APPLICATION_SERVER=/
      - SPRING_PROFILES_ACTIVE=prod
      - DATABASE_URL=jdbc:postgresql://postgres:5432/hephaestus
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
      - SECURITY_USER_NAME=admin
      - SECURITY_USER_PASSWORD=admin_password
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=hephaestus
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - '5432'
