// @ts-nocheck
// This file is auto-generated by drizzle-kit introspect.
// Do not edit manually - run `npm run db:introspect` to regenerate.
import { relations } from "drizzle-orm/relations";
import {
	badPracticeDetection,
	badPracticeFeedback,
	chatMessage,
	chatMessagePart,
	chatThread,
	contributionEvent,
	document,
	issue,
	issueAssignee,
	issueBlocking,
	issueComment,
	issueLabel,
	issueType,
	label,
	milestone,
	organization,
	pullRequestRequestedReviewers,
	pullRequestReview,
	pullRequestReviewComment,
	pullRequestReviewThread,
	pullrequestbadpractice,
	repository,
	repositoryCollaborator,
	repositoryToMonitor,
	team,
	teamLabels,
	teamMembership,
	teamRepositoryPermission,
	user,
	workspace,
	workspaceMembership,
	workspaceSlugHistory,
} from "./schema";

export const milestoneRelations = relations(milestone, ({ one, many }) => ({
	repository: one(repository, {
		fields: [milestone.repositoryId],
		references: [repository.id],
	}),
	user: one(user, {
		fields: [milestone.creatorId],
		references: [user.id],
	}),
	issues: many(issue),
}));

export const repositoryRelations = relations(repository, ({ one, many }) => ({
	milestones: many(milestone),
	organization: one(organization, {
		fields: [repository.organizationId],
		references: [organization.id],
	}),
	issues: many(issue),
	labels: many(label),
	repositoryCollaborators: many(repositoryCollaborator),
	teamRepositoryPermissions: many(teamRepositoryPermission),
}));

export const userRelations = relations(user, ({ many }) => ({
	milestones: many(milestone),
	issueComments: many(issueComment),
	pullRequestReviews: many(pullRequestReview),
	pullRequestReviewComments: many(pullRequestReviewComment),
	issues_mergedById: many(issue, {
		relationName: "issue_mergedById_user_id",
	}),
	issues_authorId: many(issue, {
		relationName: "issue_authorId_user_id",
	}),
	chatThreads: many(chatThread),
	pullRequestReviewThreads: many(pullRequestReviewThread),
	contributionEvents: many(contributionEvent),
	issueAssignees: many(issueAssignee),
	pullRequestRequestedReviewers: many(pullRequestRequestedReviewers),
	teamMemberships: many(teamMembership),
	repositoryCollaborators: many(repositoryCollaborator),
	workspaceMemberships: many(workspaceMembership),
	documents: many(document),
}));

export const organizationRelations = relations(organization, ({ many }) => ({
	repositories: many(repository),
	workspaces: many(workspace),
	issueTypes: many(issueType),
}));

export const issueCommentRelations = relations(issueComment, ({ one }) => ({
	issue: one(issue, {
		fields: [issueComment.issueId],
		references: [issue.id],
	}),
	user: one(user, {
		fields: [issueComment.authorId],
		references: [user.id],
	}),
}));

export const issueRelations = relations(issue, ({ one, many }) => ({
	issueComments: many(issueComment),
	pullRequestReviews: many(pullRequestReview),
	pullRequestReviewComments: many(pullRequestReviewComment),
	repository: one(repository, {
		fields: [issue.repositoryId],
		references: [repository.id],
	}),
	milestone: one(milestone, {
		fields: [issue.milestoneId],
		references: [milestone.id],
	}),
	user_mergedById: one(user, {
		fields: [issue.mergedById],
		references: [user.id],
		relationName: "issue_mergedById_user_id",
	}),
	user_authorId: one(user, {
		fields: [issue.authorId],
		references: [user.id],
		relationName: "issue_authorId_user_id",
	}),
	issue: one(issue, {
		fields: [issue.parentIssueId],
		references: [issue.id],
		relationName: "issue_parentIssueId_issue_id",
	}),
	issues: many(issue, {
		relationName: "issue_parentIssueId_issue_id",
	}),
	issueType: one(issueType, {
		fields: [issue.issueTypeId],
		references: [issueType.id],
	}),
	badPracticeDetections: many(badPracticeDetection),
	pullrequestbadpractices: many(pullrequestbadpractice),
	pullRequestReviewThreads: many(pullRequestReviewThread),
	issueLabels: many(issueLabel),
	issueAssignees: many(issueAssignee),
	pullRequestRequestedReviewers: many(pullRequestRequestedReviewers),
	issueBlockings_blockedIssueId: many(issueBlocking, {
		relationName: "issueBlocking_blockedIssueId_issue_id",
	}),
	issueBlockings_blockingIssueId: many(issueBlocking, {
		relationName: "issueBlocking_blockingIssueId_issue_id",
	}),
}));

export const pullRequestReviewRelations = relations(pullRequestReview, ({ one, many }) => ({
	user: one(user, {
		fields: [pullRequestReview.authorId],
		references: [user.id],
	}),
	issue: one(issue, {
		fields: [pullRequestReview.pullRequestId],
		references: [issue.id],
	}),
	pullRequestReviewComments: many(pullRequestReviewComment),
}));

export const pullRequestReviewCommentRelations = relations(
	pullRequestReviewComment,
	({ one, many }) => ({
		pullRequestReview: one(pullRequestReview, {
			fields: [pullRequestReviewComment.reviewId],
			references: [pullRequestReview.id],
		}),
		issue: one(issue, {
			fields: [pullRequestReviewComment.pullRequestId],
			references: [issue.id],
		}),
		user: one(user, {
			fields: [pullRequestReviewComment.authorId],
			references: [user.id],
		}),
		pullRequestReviewThread: one(pullRequestReviewThread, {
			fields: [pullRequestReviewComment.threadId],
			references: [pullRequestReviewThread.id],
			relationName: "pullRequestReviewComment_threadId_pullRequestReviewThread_id",
		}),
		pullRequestReviewComment: one(pullRequestReviewComment, {
			fields: [pullRequestReviewComment.inReplyToId],
			references: [pullRequestReviewComment.id],
			relationName: "pullRequestReviewComment_inReplyToId_pullRequestReviewComment_id",
		}),
		pullRequestReviewComments: many(pullRequestReviewComment, {
			relationName: "pullRequestReviewComment_inReplyToId_pullRequestReviewComment_id",
		}),
		pullRequestReviewThreads: many(pullRequestReviewThread, {
			relationName: "pullRequestReviewThread_rootCommentId_pullRequestReviewComment_id",
		}),
	}),
);

export const pullRequestReviewThreadRelations = relations(
	pullRequestReviewThread,
	({ one, many }) => ({
		pullRequestReviewComments: many(pullRequestReviewComment, {
			relationName: "pullRequestReviewComment_threadId_pullRequestReviewThread_id",
		}),
		issue: one(issue, {
			fields: [pullRequestReviewThread.pullRequestId],
			references: [issue.id],
		}),
		pullRequestReviewComment: one(pullRequestReviewComment, {
			fields: [pullRequestReviewThread.rootCommentId],
			references: [pullRequestReviewComment.id],
			relationName: "pullRequestReviewThread_rootCommentId_pullRequestReviewComment_id",
		}),
		user: one(user, {
			fields: [pullRequestReviewThread.resolvedById],
			references: [user.id],
		}),
	}),
);

export const issueTypeRelations = relations(issueType, ({ one, many }) => ({
	issues: many(issue),
	organization: one(organization, {
		fields: [issueType.organizationId],
		references: [organization.id],
	}),
}));

export const labelRelations = relations(label, ({ one, many }) => ({
	repository: one(repository, {
		fields: [label.repositoryId],
		references: [repository.id],
	}),
	issueLabels: many(issueLabel),
	teamLabels: many(teamLabels),
}));

export const badPracticeFeedbackRelations = relations(badPracticeFeedback, ({ one }) => ({
	pullrequestbadpractice: one(pullrequestbadpractice, {
		fields: [badPracticeFeedback.pullRequestBadPracticeId],
		references: [pullrequestbadpractice.id],
	}),
}));

export const pullrequestbadpracticeRelations = relations(
	pullrequestbadpractice,
	({ one, many }) => ({
		badPracticeFeedbacks: many(badPracticeFeedback),
		issue: one(issue, {
			fields: [pullrequestbadpractice.pullrequestId],
			references: [issue.id],
		}),
		badPracticeDetection: one(badPracticeDetection, {
			fields: [pullrequestbadpractice.badPracticeDetectionId],
			references: [badPracticeDetection.id],
		}),
	}),
);

export const badPracticeDetectionRelations = relations(badPracticeDetection, ({ one, many }) => ({
	issue: one(issue, {
		fields: [badPracticeDetection.pullrequestId],
		references: [issue.id],
	}),
	pullrequestbadpractices: many(pullrequestbadpractice),
}));

export const workspaceRelations = relations(workspace, ({ one, many }) => ({
	organization: one(organization, {
		fields: [workspace.organizationId],
		references: [organization.id],
	}),
	repositoryToMonitors: many(repositoryToMonitor),
	chatThreads: many(chatThread),
	workspaceSlugHistories: many(workspaceSlugHistory),
	workspaceMemberships: many(workspaceMembership),
	documents: many(document),
}));

export const repositoryToMonitorRelations = relations(repositoryToMonitor, ({ one }) => ({
	workspace: one(workspace, {
		fields: [repositoryToMonitor.workspaceId],
		references: [workspace.id],
	}),
}));

export const chatThreadRelations = relations(chatThread, ({ one, many }) => ({
	chatMessage: one(chatMessage, {
		fields: [chatThread.selectedLeafMessageId],
		references: [chatMessage.id],
		relationName: "chatThread_selectedLeafMessageId_chatMessage_id",
	}),
	user: one(user, {
		fields: [chatThread.userId],
		references: [user.id],
	}),
	workspace: one(workspace, {
		fields: [chatThread.workspaceId],
		references: [workspace.id],
	}),
	chatMessages: many(chatMessage, {
		relationName: "chatMessage_threadId_chatThread_id",
	}),
}));

export const chatMessageRelations = relations(chatMessage, ({ one, many }) => ({
	chatThreads: many(chatThread, {
		relationName: "chatThread_selectedLeafMessageId_chatMessage_id",
	}),
	chatThread: one(chatThread, {
		fields: [chatMessage.threadId],
		references: [chatThread.id],
		relationName: "chatMessage_threadId_chatThread_id",
	}),
	chatMessage: one(chatMessage, {
		fields: [chatMessage.parentMessageId],
		references: [chatMessage.id],
		relationName: "chatMessage_parentMessageId_chatMessage_id",
	}),
	chatMessages: many(chatMessage, {
		relationName: "chatMessage_parentMessageId_chatMessage_id",
	}),
	chatMessageParts: many(chatMessagePart),
}));

export const workspaceSlugHistoryRelations = relations(workspaceSlugHistory, ({ one }) => ({
	workspace: one(workspace, {
		fields: [workspaceSlugHistory.workspaceId],
		references: [workspace.id],
	}),
}));

export const contributionEventRelations = relations(contributionEvent, ({ one }) => ({
	user: one(user, {
		fields: [contributionEvent.actorId],
		references: [user.id],
	}),
}));

export const issueLabelRelations = relations(issueLabel, ({ one }) => ({
	issue: one(issue, {
		fields: [issueLabel.issueId],
		references: [issue.id],
	}),
	label: one(label, {
		fields: [issueLabel.labelId],
		references: [label.id],
	}),
}));

export const issueAssigneeRelations = relations(issueAssignee, ({ one }) => ({
	user: one(user, {
		fields: [issueAssignee.userId],
		references: [user.id],
	}),
	issue: one(issue, {
		fields: [issueAssignee.issueId],
		references: [issue.id],
	}),
}));

export const pullRequestRequestedReviewersRelations = relations(
	pullRequestRequestedReviewers,
	({ one }) => ({
		issue: one(issue, {
			fields: [pullRequestRequestedReviewers.pullRequestId],
			references: [issue.id],
		}),
		user: one(user, {
			fields: [pullRequestRequestedReviewers.userId],
			references: [user.id],
		}),
	}),
);

export const teamLabelsRelations = relations(teamLabels, ({ one }) => ({
	team: one(team, {
		fields: [teamLabels.teamId],
		references: [team.id],
	}),
	label: one(label, {
		fields: [teamLabels.labelId],
		references: [label.id],
	}),
}));

export const teamRelations = relations(team, ({ many }) => ({
	teamLabels: many(teamLabels),
	teamMemberships: many(teamMembership),
	teamRepositoryPermissions: many(teamRepositoryPermission),
}));

export const issueBlockingRelations = relations(issueBlocking, ({ one }) => ({
	issue_blockedIssueId: one(issue, {
		fields: [issueBlocking.blockedIssueId],
		references: [issue.id],
		relationName: "issueBlocking_blockedIssueId_issue_id",
	}),
	issue_blockingIssueId: one(issue, {
		fields: [issueBlocking.blockingIssueId],
		references: [issue.id],
		relationName: "issueBlocking_blockingIssueId_issue_id",
	}),
}));

export const teamMembershipRelations = relations(teamMembership, ({ one }) => ({
	user: one(user, {
		fields: [teamMembership.userId],
		references: [user.id],
	}),
	team: one(team, {
		fields: [teamMembership.teamId],
		references: [team.id],
	}),
}));

export const repositoryCollaboratorRelations = relations(repositoryCollaborator, ({ one }) => ({
	repository: one(repository, {
		fields: [repositoryCollaborator.repositoryId],
		references: [repository.id],
	}),
	user: one(user, {
		fields: [repositoryCollaborator.userId],
		references: [user.id],
	}),
}));

export const teamRepositoryPermissionRelations = relations(teamRepositoryPermission, ({ one }) => ({
	team: one(team, {
		fields: [teamRepositoryPermission.teamId],
		references: [team.id],
	}),
	repository: one(repository, {
		fields: [teamRepositoryPermission.repositoryId],
		references: [repository.id],
	}),
}));

export const chatMessagePartRelations = relations(chatMessagePart, ({ one }) => ({
	chatMessage: one(chatMessage, {
		fields: [chatMessagePart.messageId],
		references: [chatMessage.id],
	}),
}));

export const workspaceMembershipRelations = relations(workspaceMembership, ({ one }) => ({
	user: one(user, {
		fields: [workspaceMembership.userId],
		references: [user.id],
	}),
	workspace: one(workspace, {
		fields: [workspaceMembership.workspaceId],
		references: [workspace.id],
	}),
}));

export const documentRelations = relations(document, ({ one }) => ({
	user: one(user, {
		fields: [document.userId],
		references: [user.id],
	}),
	workspace: one(workspace, {
		fields: [document.workspaceId],
		references: [workspace.id],
	}),
}));
