query GetRepositoryPRs($owner: String!, $name: String!, $first: Int!) {
	repository(owner: $owner, name: $name) {
		githubId: id
		name
		nameWithOwner
		description
		url
		pullRequests(first: $first, states: [OPEN, MERGED]) {
			nodes {
				githubId: id
				title
				url
				state
				createdAt
				updatedAt
				mergedAt
				author {
					...authorFields
				}
				comments(last: 100) {
					nodes {
						githubId: id
						body
						createdAt
						updatedAt
						author {
							...authorFields
						}
					}
				}
			}
		}
	}
}

fragment authorFields on Actor {
	avatarUrl
	login
	url
}
