services:
  webhook-ingest:
    build: .
    ports:
      - "4200"
    environment:
      # For production use tls://<host>
      - NATS_URL=${NATS_URL:-nats://nats-server:4222}
      - NATS_AUTH_TOKEN
      - WEBHOOK_SECRET
    depends_on:
      nats-server:
        condition: service_healthy
    networks:
      - common-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nats-server:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--config", "/etc/nats/nats-server.conf"]
    environment:
      - TLS_CERT_FILE
      - TLS_KEY_FILE
      - NATS_AUTH_TOKEN
    volumes:
      - nats_data:/data
      - ./nats-server.conf:/etc/nats/nats-server.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - common-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  common-network:

volumes:
  nats_data: 
