services:
  webhook-ingest:
    build: .
    ports:
      - "4200:4200"
    environment:
      # For production use tls://<host>
      - NATS_URL=${NATS_URL:-nats://nats-server:4222}
      - NATS_AUTH_TOKEN
      - GITHUB_WEBHOOK_SECRET
      - GITLAB_WEBHOOK_SECRET
    depends_on:
      nats-server:
        condition: service_healthy
    networks:
      - common-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nats-server:
    image: nats:alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--config", "/etc/nats/nats-server.conf"]
    volumes:
      - nats_data:/data
    configs:
      - source: nats-server.conf
        target: /etc/nats/nats-server.conf
    networks:
      - common-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8222/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  common-network:

volumes:
  nats_data: 

configs:
  nats-server.conf:
    content: |
      listen: "0.0.0.0:4222" 

      http_port: 8222

      jetstream {
        store_dir: "/data"
        max_memory_store: 4GB
        max_file_store: 50GB
      }

