openapi: 3.0.1
info:
  title: Hephaestus Intelligence API
  description: API documentation for the Hephaestus intelligence service.
  contact:
    name: Felix T.J. Dietrich
    email: felixtj.dietrich@tum.de
  license:
    name: MIT License
    url: https://github.com/ls1intum/Hephaestus/blob/develop/LICENSE
  version: 0.0.1
servers:
    - url: http://localhost:8080
      description: Local development server
paths:
  /chat:
    post:
      summary: Chat with LLM
      operationId: chatWithLLM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response from LLM
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ChatRequest:
      type: object
      properties:
        message:
          type: string
          description: The message to be sent to the LLM
      required:
        - message
    ChatResponse:
      type: object
      properties:
        response:
          type: string
          description: The response generated by the LLM
      required:
        - response
    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Error message in case of failure