components:
  schemas:
    ChatMessage:
      properties:
        content:
          title: Content
          type: string
        sender:
          title: Sender
          type: string
      required:
      - sender
      - content
      title: ChatMessage
      type: object
    ChatRequest:
      properties:
        message_history:
          items:
            $ref: '#/components/schemas/ChatMessage'
          title: Message History
          type: array
      required:
      - message_history
      title: ChatRequest
      type: object
    ChatResponse:
      properties:
        responce:
          title: Responce
          type: string
      required:
      - responce
      title: ChatResponse
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  contact:
    email: felixtj.dietrich@tum.de
    name: Felix T.J. Dietrich
  description: API documentation for the Hephaestus Intelligence Service.
  title: Hephaestus Intelligence Service API
  version: 0.0.1
openapi: 3.1.0
paths:
  /chat:
    post:
      operationId: chat_chat_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Start and continue a chat session with an LLM.
