-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "databasechangelog" (
	"id" varchar(255) NOT NULL,
	"author" varchar(255) NOT NULL,
	"filename" varchar(255) NOT NULL,
	"dateexecuted" timestamp NOT NULL,
	"orderexecuted" integer NOT NULL,
	"exectype" varchar(10) NOT NULL,
	"md5sum" varchar(35),
	"description" varchar(255),
	"comments" varchar(255),
	"tag" varchar(255),
	"liquibase" varchar(20),
	"contexts" varchar(255),
	"labels" varchar(255),
	"deployment_id" varchar(10)
);
--> statement-breakpoint
CREATE TABLE "databasechangeloglock" (
	"id" integer PRIMARY KEY NOT NULL,
	"locked" boolean NOT NULL,
	"lockgranted" timestamp,
	"lockedby" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "pull_request_review" (
	"id" bigint PRIMARY KEY NOT NULL,
	"body" "oid",
	"commit_id" varchar(255),
	"html_url" varchar(255),
	"is_dismissed" boolean NOT NULL,
	"state" varchar(255),
	"submitted_at" timestamp with time zone,
	"author_id" bigint,
	"pull_request_id" bigint
);
--> statement-breakpoint
CREATE TABLE "user" (
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"avatar_url" varchar(255),
	"blog" varchar(255),
	"company" varchar(255),
	"description" varchar(255),
	"email" varchar(255),
	"followers" integer NOT NULL,
	"following" integer NOT NULL,
	"html_url" varchar(255),
	"location" varchar(255),
	"login" varchar(255),
	"name" varchar(255),
	"type" varchar(255),
	"league_points" integer DEFAULT 0 NOT NULL,
	"notifications_enabled" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "issue_comment" (
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"author_association" varchar(255),
	"body" "oid",
	"html_url" varchar(255),
	"author_id" bigint,
	"issue_id" bigint
);
--> statement-breakpoint
CREATE TABLE "milestone" (
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"closed_at" timestamp with time zone,
	"description" "oid",
	"due_on" timestamp with time zone,
	"html_url" varchar(255),
	"number" integer NOT NULL,
	"state" varchar(255),
	"title" varchar(255),
	"creator_id" bigint,
	"repository_id" bigint
);
--> statement-breakpoint
CREATE TABLE "repository" (
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"default_branch" varchar(255),
	"description" varchar(255),
	"has_issues" boolean NOT NULL,
	"has_projects" boolean NOT NULL,
	"has_wiki" boolean NOT NULL,
	"homepage" varchar(255),
	"html_url" varchar(255),
	"is_archived" boolean NOT NULL,
	"is_disabled" boolean NOT NULL,
	"is_private" boolean NOT NULL,
	"name" varchar(255),
	"name_with_owner" varchar(255),
	"pushed_at" timestamp with time zone,
	"stargazers_count" integer NOT NULL,
	"visibility" varchar(255),
	"watchers_count" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pull_request_review_comment" (
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"author_association" varchar(255),
	"body" "oid",
	"commit_id" varchar(255),
	"diff_hunk" "oid",
	"html_url" varchar(255),
	"line" integer NOT NULL,
	"original_commit_id" varchar(255),
	"original_line" integer NOT NULL,
	"original_position" integer NOT NULL,
	"original_start_line" integer,
	"path" varchar(255),
	"position" integer NOT NULL,
	"side" varchar(255),
	"start_line" integer,
	"start_side" varchar(255),
	"author_id" bigint,
	"pull_request_id" bigint,
	"review_id" bigint
);
--> statement-breakpoint
CREATE TABLE "issue" (
	"issue_type" varchar(31) NOT NULL,
	"id" bigint PRIMARY KEY NOT NULL,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"body" "oid",
	"closed_at" timestamp with time zone,
	"comments_count" integer NOT NULL,
	"html_url" varchar(255),
	"is_locked" boolean NOT NULL,
	"number" integer NOT NULL,
	"state" varchar(255),
	"title" varchar(255),
	"additions" integer,
	"changed_files" integer,
	"commits" integer,
	"deletions" integer,
	"is_draft" boolean,
	"is_mergeable" boolean,
	"is_merged" boolean,
	"maintainer_can_modify" boolean,
	"merge_commit_sha" varchar(255),
	"mergeable_state" varchar(255),
	"merged_at" timestamp with time zone,
	"author_id" bigint,
	"milestone_id" bigint,
	"repository_id" bigint,
	"merged_by_id" bigint,
	"has_pull_request" boolean NOT NULL,
	"last_sync_at" timestamp(6),
	"bad_practice_summary" "oid",
	"last_detection_time" timestamp(6) with time zone
);
--> statement-breakpoint
CREATE TABLE "label" (
	"id" bigint PRIMARY KEY NOT NULL,
	"color" varchar(255),
	"description" varchar(255),
	"name" varchar(255),
	"repository_id" bigint
);
--> statement-breakpoint
CREATE TABLE "team" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "team_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"name" varchar(255),
	"hidden" boolean DEFAULT false NOT NULL,
	"created_at" timestamp(6) with time zone,
	"description" text,
	"html_url" text,
	"last_synced_at" timestamp(6) with time zone,
	"organization" varchar(255),
	"parent_id" bigint,
	"privacy" varchar(32),
	"updated_at" timestamp(6) with time zone
);
--> statement-breakpoint
CREATE TABLE "workspace" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "workspace_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"users_synced_at" timestamp(6)
);
--> statement-breakpoint
CREATE TABLE "repository_to_monitor" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "repository_to_monitor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"issues_and_pull_requests_synced_at" timestamp(6),
	"labels_synced_at" timestamp(6),
	"milestones_synced_at" timestamp(6),
	"name_with_owner" varchar(255),
	"repository_synced_at" timestamp(6),
	"workspace_id" bigint
);
--> statement-breakpoint
CREATE TABLE "pullrequestbadpractice" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pullrequestbadpractice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"description" "oid",
	"title" varchar(255),
	"pullrequest_id" bigint,
	"state" smallint DEFAULT 0,
	"detection_time" timestamp(6) with time zone,
	"last_update_time" timestamp(6) with time zone,
	"user_state" smallint,
	"detection_pullrequest_lifecycle_state" smallint,
	"detection_trace_id" varchar(255),
	"bad_practice_detection_id" bigint
);
--> statement-breakpoint
CREATE TABLE "bad_practice_feedback" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bad_practice_feedback_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"explanation" "oid",
	"type" varchar(255),
	"pull_request_bad_practice_id" bigint,
	"creation_time" timestamp(6) with time zone
);
--> statement-breakpoint
CREATE TABLE "bad_practice_detection" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bad_practice_detection_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"detection_time" timestamp(6) with time zone,
	"summary" "oid",
	"trace_id" varchar(255),
	"pullrequest_id" bigint
);
--> statement-breakpoint
CREATE TABLE "chat_message_vote" (
	"message_id" uuid PRIMARY KEY NOT NULL,
	"created_at" timestamp(6) with time zone NOT NULL,
	"is_upvoted" boolean NOT NULL,
	"updated_at" timestamp(6) with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chat_message" (
	"id" uuid PRIMARY KEY NOT NULL,
	"created_at" timestamp(6) with time zone NOT NULL,
	"metadata" jsonb,
	"role" varchar(16) NOT NULL,
	"parent_message_id" uuid,
	"thread_id" uuid NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chat_thread" (
	"id" uuid PRIMARY KEY NOT NULL,
	"created_at" timestamp(6) with time zone NOT NULL,
	"title" text,
	"selected_leaf_message_id" uuid,
	"user_id" bigint,
	CONSTRAINT "uc_chat_threadselected_leaf_message_id_col" UNIQUE("selected_leaf_message_id")
);
--> statement-breakpoint
CREATE TABLE "issue_label" (
	"issue_id" bigint NOT NULL,
	"label_id" bigint NOT NULL,
	CONSTRAINT "issue_label_pkey" PRIMARY KEY("issue_id","label_id")
);
--> statement-breakpoint
CREATE TABLE "issue_assignee" (
	"issue_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "issue_assignee_pkey" PRIMARY KEY("issue_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "pull_request_requested_reviewers" (
	"pull_request_id" bigint NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "pull_request_requested_reviewers_pkey" PRIMARY KEY("pull_request_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "team_labels" (
	"team_id" bigint NOT NULL,
	"label_id" bigint NOT NULL,
	CONSTRAINT "team_labelsPK" PRIMARY KEY("team_id","label_id")
);
--> statement-breakpoint
CREATE TABLE "team_membership" (
	"role" varchar(32),
	"user_id" bigint NOT NULL,
	"team_id" bigint NOT NULL,
	CONSTRAINT "team_membershipPK" PRIMARY KEY("user_id","team_id")
);
--> statement-breakpoint
CREATE TABLE "team_repository_permission" (
	"permission" varchar(32) NOT NULL,
	"repository_id" bigint NOT NULL,
	"team_id" bigint NOT NULL,
	CONSTRAINT "team_repository_permissionPK" PRIMARY KEY("repository_id","team_id")
);
--> statement-breakpoint
CREATE TABLE "chat_message_part" (
	"message_id" uuid NOT NULL,
	"order_index" integer NOT NULL,
	"content" jsonb,
	"original_type" varchar(128),
	"type" varchar(32) NOT NULL,
	CONSTRAINT "chat_message_partPK" PRIMARY KEY("message_id","order_index")
);
--> statement-breakpoint
CREATE TABLE "document" (
	"id" uuid NOT NULL,
	"version_number" integer NOT NULL,
	"content" text,
	"created_at" timestamp(6) with time zone NOT NULL,
	"kind" varchar(255) NOT NULL,
	"title" varchar(255) NOT NULL,
	"user_id" bigint NOT NULL,
	CONSTRAINT "documentPK" PRIMARY KEY("id","version_number")
);
--> statement-breakpoint
ALTER TABLE "pull_request_review" ADD CONSTRAINT "fkeehfcwrodfu61gremlcvhgir5" FOREIGN KEY ("author_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pull_request_review" ADD CONSTRAINT "fkio96gq2jetvy6a4in9nl8vkvd" FOREIGN KEY ("pull_request_id") REFERENCES "public"."issue"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_comment" ADD CONSTRAINT "fk8wy5rxggrte2ntcq80g7o7210" FOREIGN KEY ("issue_id") REFERENCES "public"."issue"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_comment" ADD CONSTRAINT "fkdy6oeojymud1wna20olqgyt31" FOREIGN KEY ("author_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "milestone" ADD CONSTRAINT "fkbjhs37s6qmqtd330gu9mit6w0" FOREIGN KEY ("repository_id") REFERENCES "public"."repository"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "milestone" ADD CONSTRAINT "fkg6ieho7gomiumy85puy6l13f1" FOREIGN KEY ("creator_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pull_request_review_comment" ADD CONSTRAINT "fkbx1g5jpdegymhyv9pbk2jdgfw" FOREIGN KEY ("review_id") REFERENCES "public"."pull_request_review"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pull_request_review_comment" ADD CONSTRAINT "fkohqvdiswptbm0h8cniq7r1tgq" FOREIGN KEY ("pull_request_id") REFERENCES "public"."issue"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pull_request_review_comment" ADD CONSTRAINT "fktl08ieowbl171xem2bciho7kw" FOREIGN KEY ("author_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue" ADD CONSTRAINT "fk76s4b6ncspm9bk35y49xh4s9t" FOREIGN KEY ("repository_id") REFERENCES "public"."repository"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue" ADD CONSTRAINT "fk7t1o4tuel06m9bn4dppqmiod6" FOREIGN KEY ("milestone_id") REFERENCES "public"."milestone"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue" ADD CONSTRAINT "fkqvnu6vslj5txt8xencru8m6x4" FOREIGN KEY ("merged_by_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue" ADD CONSTRAINT "fkrwr6v8fiqetuiuvfjcvie8s85" FOREIGN KEY ("author_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "label" ADD CONSTRAINT "fk2951edbl9g9y8ee1q97e2ff75" FOREIGN KEY ("repository_id") REFERENCES "public"."repository"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "repository_to_monitor" ADD CONSTRAINT "FKdkxnkm4a2wyw0d5k63gh2st64" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspace"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pullrequestbadpractice" ADD CONSTRAINT "FK1m1jhw92ublt7ya0d557sg5j" FOREIGN KEY ("pullrequest_id") REFERENCES "public"."issue"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pullrequestbadpractice" ADD CONSTRAINT "FKdn50l1oul09kq3142ku39gnlp" FOREIGN KEY ("bad_practice_detection_id") REFERENCES "public"."bad_practice_detection"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bad_practice_feedback" ADD CONSTRAINT "FK34k5tg4qb6gy4g7tn9q8uhogl" FOREIGN KEY ("pull_request_bad_practice_id") REFERENCES "public"."pullrequestbadpractice"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bad_practice_detection" ADD CONSTRAINT "FKhk2vrsr2rdq2gb3cjnvieh3nw" FOREIGN KEY ("pullrequest_id") REFERENCES "public"."issue"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_message" ADD CONSTRAINT "FK8s34d909gxc4xrlvml8gag9kh" FOREIGN KEY ("thread_id") REFERENCES "public"."chat_thread"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_message" ADD CONSTRAINT "FKd0fewjs0l68rq2bww9h8o4cmb" FOREIGN KEY ("parent_message_id") REFERENCES "public"."chat_message"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_thread" ADD CONSTRAINT "FK34beodgwi0g7kn66svlk4hlfr" FOREIGN KEY ("selected_leaf_message_id") REFERENCES "public"."chat_message"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_thread" ADD CONSTRAINT "FKikdxlx9viomcwrgxj7fbyfsew" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_label" ADD CONSTRAINT "fkit5n9c0frugu5m8xqsxtps63r" FOREIGN KEY ("issue_id") REFERENCES "public"."issue"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_label" ADD CONSTRAINT "fkxbk5rr30kkb6k4ech7x4vh9h" FOREIGN KEY ("label_id") REFERENCES "public"."label"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_assignee" ADD CONSTRAINT "fk2cfu8w8wjb9vosy4hbrme0rqe" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "issue_assignee" ADD CONSTRAINT "fkocgmsva4p5e8ic9k5dbjqa15u" FOREIGN KEY ("issue_id") REFERENCES "public"."issue"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pull_request_requested_reviewers" ADD CONSTRAINT "fk6dld06xx8rh9xhqfnca070a0i" FOREIGN KEY ("pull_request_id") REFERENCES "public"."issue"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pull_request_requested_reviewers" ADD CONSTRAINT "fkioq4g5aksr97l6qyl4g5l63tn" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_labels" ADD CONSTRAINT "FK3f9iwbjmf3gyflex7xoofnnbh" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_labels" ADD CONSTRAINT "FKa8aajjyqj8uwnqtrrbg3a9v5o" FOREIGN KEY ("label_id") REFERENCES "public"."label"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_membership" ADD CONSTRAINT "FKnkpwi3whks92uvhn5qe71v4k6" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_membership" ADD CONSTRAINT "FKrf92vmiawfvyhxcmigcg10opm" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_repository_permission" ADD CONSTRAINT "FK7qxvqq8p6690vtdux47lsg8b1" FOREIGN KEY ("team_id") REFERENCES "public"."team"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_repository_permission" ADD CONSTRAINT "FK92gtctw6ca02527qjja7gns9f" FOREIGN KEY ("repository_id") REFERENCES "public"."repository"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat_message_part" ADD CONSTRAINT "FKkfle3niou3f9r63mc3u8vi1na" FOREIGN KEY ("message_id") REFERENCES "public"."chat_message"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "document" ADD CONSTRAINT "FKjhdxdv9sijhujiynqbb5jc010" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "idx_document_created_at" ON "document" USING btree ("created_at" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "idx_document_id" ON "document" USING btree ("id" uuid_ops);--> statement-breakpoint
CREATE INDEX "idx_document_user_id" ON "document" USING btree ("user_id" int8_ops);
*/