/* tslint:disable */
/* eslint-disable */
/**
 * Hephaestus API
 * API documentation for the Hephaestus application server.
 *
 * The version of the OpenAPI document: 0.6.1
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface BadPracticeFeedback
 */
export interface BadPracticeFeedback {
    /**
     * 
     * @type {string}
     * @memberof BadPracticeFeedback
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof BadPracticeFeedback
     */
    explanation: string;
}

/**
 * Check if a given object implements the BadPracticeFeedback interface.
 */
export function instanceOfBadPracticeFeedback(value: object): value is BadPracticeFeedback {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('explanation' in value) || value['explanation'] === undefined) return false;
    return true;
}

export function BadPracticeFeedbackFromJSON(json: any): BadPracticeFeedback {
    return BadPracticeFeedbackFromJSONTyped(json, false);
}

export function BadPracticeFeedbackFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadPracticeFeedback {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'explanation': json['explanation'],
    };
}

export function BadPracticeFeedbackToJSON(value?: BadPracticeFeedback | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'explanation': value['explanation'],
    };
}

