// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Hephaestus API
 * API documentation for the Hephaestus application server.
 *
 * The version of the OpenAPI document: 0.6.1
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    login: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    avatarUrl: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    htmlUrl: string;
    /**
     * 
     * @type {number}
     * @memberof UserInfo
     */
    leaguePoints?: number;
}

/**
 * Check if a given object implements the UserInfo interface.
 */
export function instanceOfUserInfo(value: object): value is UserInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('login' in value) || value['login'] === undefined) return false;
    if (!('avatarUrl' in value) || value['avatarUrl'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('htmlUrl' in value) || value['htmlUrl'] === undefined) return false;
    return true;
}

export function UserInfoFromJSON(json: any): UserInfo {
    return UserInfoFromJSONTyped(json, false);
}

export function UserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'login': json['login'],
        'email': json['email'] == null ? undefined : json['email'],
        'avatarUrl': json['avatarUrl'],
        'name': json['name'],
        'htmlUrl': json['htmlUrl'],
        'leaguePoints': json['leaguePoints'] == null ? undefined : json['leaguePoints'],
    };
}

export function UserInfoToJSON(value?: UserInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'login': value['login'],
        'email': value['email'],
        'avatarUrl': value['avatarUrl'],
        'name': value['name'],
        'htmlUrl': value['htmlUrl'],
        'leaguePoints': value['leaguePoints'],
    };
}

