name: 🐞 Bug Report
description: Something isn't working as expected
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the sections below to help us fix this quickly.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected instead.
      placeholder: "When I click X, Y happens. I expected Z."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      placeholder: |
        1. Go to /leaderboard
        2. Click on "Weekly" tab
        3. See error in console
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Hephaestus is affected?
      options:
        - Webapp (React frontend)
        - Application Server (Java/Spring)
        - Intelligence Service (Python/AI)
        - Webhook Ingest
        - Don't know
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, or deployment details if relevant.
      placeholder: "Chrome 120, macOS 14, production"

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste error messages, console output, or attach screenshots.
      render: shell

  - type: dropdown
    id: contribute
    attributes:
      label: Willing to contribute a fix?
      options:
        - "Yes"
        - "No"
    validations:
      required: false
