name: 🐞 Bug Report
description: Create a bug report to help us improve
title: "bug: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is and what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior (e.g., 1. Go to '...', 2. Click on '...', 3. See error)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please share relevant environment details:
        - Component (webapp, server, etc.)
        - Browser and version (if applicable)
        - OS (if relevant)
      placeholder: |
        - Component: webapp
        - Browser: Chrome 120
        - OS: macOS
  - type: textarea
    attributes:
      label: Additional information
      description: Add screenshots, logs, or any other context about the problem here.
  - type: dropdown
    id: contribute
    attributes:
      label: Would you like to contribute a fix?
      description: If this is confirmed as a bug, we're happy to provide guidance and review support.
      options:
        - "No"
        - "Yes"
    validations:
      required: true
