name: 🐞 Bug
description: Something is broken
title: ""
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What's broken?
      placeholder: "X doesn't work when Y. Expected Z."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Steps or link to reproduce. No repro = likely won't get fixed.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Webapp
        - Server
        - AI Service
        - Webhooks
        - Unknown
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Logs / Screenshots
      description: Console errors, stack traces, or screenshots.
      render: shell
