services:
  webhook-ingest:
    image: "ghcr.io/ls1intum/hephaestus/webhook-ingest:${IMAGE_TAG}"
    ports:
      - "4200"
    environment:
      # For production use tls://<host>
      NATS_URL: ${NATS_URL}
      NATS_AUTH_TOKEN: ${NATS_AUTH_TOKEN}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
    env_file:
      - .env.prod.core
    depends_on:
      nats-server:
        condition: service_healthy
    networks:
      - core-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  keycloak:
    image: keycloak
    # TODO: !!!

  nats-server:
    image: nats:alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--config", "/etc/nats/nats-server.conf"]
    environment:
      TLS_CERT_FILE: ${TLS_CERT_FILE}
      TLS_KEY_FILE: ${TLS_KEY_FILE}
      NATS_AUTH_TOKEN: ${NATS_AUTH_TOKEN}
    env_file:
      - .env.prod.core
    volumes:
      - nats_data:/data
      - ./nats-server.conf:/etc/nats/nats-server.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - core-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8222/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 3s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  core-network:

volumes:
  nats_data: 
