@startuml
left to right direction
skinparam backgroundColor transparent
skinparam packageStyle rectangle

actor Developer
actor "Project Manager" as PM
actor "Scrum Master" as SM
actor "Product Owner" as PO

rectangle "Hephaestus System - Collaboration" {
  usecase "Facilitate Stand-up Meetings" as FSM
  usecase "Assist Sprint Planning" as ASP
  usecase "Conduct Sprint Retrospectives" as CSR
  usecase "Manage Sprint Backlogs" as MSB
  usecase "Track Sprint Progress" as TSP
  usecase "Generate Collaboration Insights" as GCI
  usecase "Facilitate Cross-team Collaboration" as FCC
  usecase "Schedule Collaboration Sessions" as SCS
}

Developer --> FSM
Developer --> ASP
Developer --> CSR
Developer --> MSB
Developer --> TSP
Developer --> FCC

PM -up--> ASP
PM -up--> MSB
PM -up--> TSP
PM -up--> GCI
PM -up--> FCC

SM -up-> FSM
SM -up-> ASP
SM -up-> CSR
SM -up-> MSB
SM -up-> TSP
SM -up-> GCI
SM -up-> FCC
SM -up-> SCS

PO ---> ASP
PO ---> CSR
PO ---> MSB
PO ---> TSP
PO ---> GCI
PO ---> FCC

@enduml
