@startuml
left to right direction
skinparam backgroundColor transparent
skinparam packageStyle rectangle

actor "Project Manager" as PM
actor Developer
actor "Product Owner" as PO
actor "Scrum Master" as SM
actor "QA Engineer" as QA

rectangle "Hephaestus System - Design" {
  usecase "Define System Architecture" as DSA
  usecase "Design Database Schema" as DDS
  usecase "Create UI/UX Prototypes" as CUP
  usecase "Review and Approve Designs" as RAD
  usecase "Generate Design Documentation" as GDD
  usecase "Validate Design" as VD
}

PM -up-> DSA
PM -up-> RAD
PM -up--> GDD

Developer --> DSA
Developer --> DDS
Developer --> CUP
Developer --> VD

PO ---> CUP
PO ---> RAD
PO ---> VD

SM --> RAD
SM --> VD

QA -up-> RAD
QA -up-> VD
@enduml
