name: 'Setup Advanced Caches'
description: 'Sets up intelligent caching for CI/CD pipeline optimization'
inputs:
  cache-type:
    description: 'Type of cache to setup'
    required: true
  os:
    description: 'Operating system for cache key'
    required: false
    default: 'ubuntu-latest'

runs:
  using: "composite"
  steps:
    # Node.js caching
    - name: Setup Node.js
      if: contains(fromJSON('["application-server-quality", "webapp-quality", "webapp-visual", "openapi-validation", "docs-quality", "intelligence-service-quality", "webhook-ingest-quality"]'), inputs.cache-type)
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: "npm"

    - name: Cache Node.js dependencies
      if: contains(fromJSON('["application-server-quality", "webapp-quality", "webapp-visual", "openapi-validation", "webhook-ingest-quality"]'), inputs.cache-type)
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          webapp/node_modules
          server/webhook-ingest/node_modules
          node_modules
        key: ${{ inputs.os }}-node-${{ hashFiles('package-lock.json', 'webapp/package-lock.json', 'server/webhook-ingest/package-lock.json', 'webapp/biome.json', 'webapp/tsconfig.json', 'webapp/vite.config.js', 'webapp/components.json') }}-${{ inputs.cache-type }}
        restore-keys: |
          ${{ inputs.os }}-node-${{ hashFiles('package-lock.json', 'webapp/package-lock.json', 'server/webhook-ingest/package-lock.json') }}-${{ inputs.cache-type }}
          ${{ inputs.os }}-node-${{ hashFiles('package-lock.json', 'webapp/package-lock.json') }}-${{ inputs.cache-type }}


    # Java/Maven caching
    - name: Set up JDK 21
      if: contains(fromJSON('["application-server-unit", "application-server-integration", "application-server-architecture", "application-server-quality", "openapi-validation", "database-schema-validation", "database-documentation-validation", "database-models-validation"]'), inputs.cache-type)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: maven

    - name: Cache Maven dependencies
      if: contains(fromJSON('["application-server-unit", "application-server-integration", "application-server-architecture", "application-server-quality", "openapi-validation", "database-schema-validation", "database-documentation-validation", "database-models-validation"]'), inputs.cache-type)
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          server/application-server/target
        key: ${{ inputs.os }}-maven-${{ hashFiles('server/application-server/pom.xml') || 'no-pom' }}-${{ inputs.cache-type }}
        restore-keys: |
          ${{ inputs.os }}-maven-${{ hashFiles('server/application-server/pom.xml') || 'no-pom' }}-
          ${{ inputs.os }}-maven-
