name: "Setup Advanced Caches"
description: "Sets up intelligent caching for CI/CD pipeline optimization"
inputs:
  cache-type:
    description: "Type of cache to setup"
    required: true
  os:
    description: "Operating system for cache key"
    required: false
    default: "ubuntu-latest"

runs:
  using: "composite"
  steps:
    # Node.js caching
    - name: Setup Node.js
      if: contains(fromJSON('["application-server-quality", "webapp-quality", "webapp-visual", "webapp-unit", "webapp-storybook", "openapi-validation", "intelligence-service-quality", "intelligence-service-unit", "intelligence-service-integration", "webhook-ingest-quality", "webhook-ingest-unit"]'), inputs.cache-type)
      uses: actions/setup-node@v4
      with:
        node-version-file: ".node-version"
        cache: "npm"

    - name: Cache Node.js dependencies
      if: contains(fromJSON('["application-server-quality", "webapp-quality", "webapp-visual", "webapp-unit", "webapp-storybook", "openapi-validation", "webhook-ingest-quality", "webhook-ingest-unit", "intelligence-service-quality", "intelligence-service-unit", "intelligence-service-integration"]'), inputs.cache-type)
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          webapp/node_modules
          server/webhook-ingest/node_modules
          server/intelligence-service/node_modules
          node_modules
        key: ${{ inputs.os }}-node-${{ hashFiles('package-lock.json', 'webapp/package.json', 'server/webhook-ingest/package.json', 'server/intelligence-service/package.json') }}-${{ inputs.cache-type }}
        restore-keys: |
          ${{ inputs.os }}-node-${{ hashFiles('package-lock.json') }}-${{ inputs.cache-type }}
          ${{ inputs.os }}-node-

    # Java/Maven caching
    - name: Set up JDK 21
      if: contains(fromJSON('["application-server-unit", "application-server-integration", "application-server-architecture", "application-server-quality", "openapi-validation", "database-schema-validation", "database-documentation-validation", "database-models-validation"]'), inputs.cache-type)
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "21"
        cache: maven

    - name: Cache Maven dependencies
      if: contains(fromJSON('["application-server-unit", "application-server-integration", "application-server-architecture", "application-server-quality", "openapi-validation", "database-schema-validation", "database-documentation-validation", "database-models-validation"]'), inputs.cache-type)
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          server/application-server/target/classes
          server/application-server/target/test-classes
          server/application-server/target/generated-sources
          server/application-server/target/maven-status
        key: ${{ inputs.os }}-maven-${{ hashFiles('server/application-server/pom.xml') || 'no-pom' }}-${{ inputs.cache-type }}
        restore-keys: |
          ${{ inputs.os }}-maven-${{ hashFiles('server/application-server/pom.xml') || 'no-pom' }}-
          ${{ inputs.os }}-maven-

    # Playwright browser caching for Storybook tests
    - name: Cache Playwright browsers
      id: playwright-cache
      if: inputs.cache-type == 'webapp-storybook'
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ inputs.os }}-playwright-${{ hashFiles('webapp/package-lock.json') }}
        restore-keys: |
          ${{ inputs.os }}-playwright-

    # NOTE: Playwright browser installation happens in ci-tests.yml after npm ci
    # This cache just restores browsers from previous runs if available

    # Platform-specific binary caching for Linux runners
    # These packages (@rollup/rollup-linux-x64-gnu, lightningcss-linux-x64-gnu, @biomejs/cli-linux-x64)
    # are installed via scripts/install-platform-binaries.mjs after npm ci.
    # We cache them in ~/.cache/platform-binaries and restore after npm ci wipes node_modules.
    - name: Cache platform binaries
      id: platform-cache
      if: contains(fromJSON('["webapp-quality", "webapp-visual", "webapp-unit", "webapp-storybook", "intelligence-service-quality", "intelligence-service-unit", "intelligence-service-integration", "intelligence-service-architecture", "webhook-ingest-quality", "webhook-ingest-unit"]'), inputs.cache-type) && runner.os == 'Linux'
      uses: actions/cache@v4
      with:
        path: ~/.cache/platform-binaries
        key: ${{ inputs.os }}-platform-binaries-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ inputs.os }}-platform-binaries-

    # Storybook build cache for visual tests
    - name: Cache Storybook build
      if: contains(fromJSON('["webapp-visual", "webapp-storybook"]'), inputs.cache-type)
      uses: actions/cache@v4
      with:
        path: |
          webapp/storybook-static
          webapp/.storybook/.cache
        key: ${{ inputs.os }}-storybook-${{ hashFiles('webapp/**/*.stories.tsx', 'webapp/.storybook/**', 'webapp/package-lock.json') }}
        restore-keys: |
          ${{ inputs.os }}-storybook-
