/*
 * Hephaestus API
 * API documentation for the Hephaestus intelligence service.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ChatRequest;
import org.openapitools.client.model.ChatResponse;
import org.openapitools.client.model.ErrorResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Chat with LLM
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void chatWithLLMTest() throws ApiException {
        ChatRequest chatRequest = null;
        ChatResponse response = api.chatWithLLM(chatRequest);
        // TODO: test validations
    }

}
