/**
 * Hephaestus API
 * API documentation for the Hephaestus application server.
 *
 * The version of the OpenAPI document: 0.9.0-rc.10
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A data part with dynamic type.  Note: In UI messages, data can be of any JSON type (object, array, string, number, etc.).
 */
export interface DataUIPart { 
    data: any | null;
    id?: string | null;
    type: string;
}

