/**
 * Hephaestus API
 * API documentation for the Hephaestus application server.
 *
 * The version of the OpenAPI document: 0.9.0-rc.10
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO for complete document responses.  Used when returning full document details (includes content).
 */
export interface Document { 
    content: string;
    createdAt: string;
    id: string;
    kind: Document.KindEnum;
    title: string;
    userId: string;
    versionNumber: number;
}
export namespace Document {
    export type KindEnum = 'TEXT';
    export const KindEnum = {
        Text: 'TEXT' as KindEnum
    };
}


