/**
 * PokéAPI
 * All the Pokémon data you\'ll ever need in one place, easily accessible through a modern free open-source RESTful API.  ## What is this?  This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.  We\'ve covered everything from Pokémon to Berry Flavors.  ## Where do I start?  We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.  This API will always be publicly available and will never require any extensive setup process to consume.  Created by [**Paul Hallett**(]https://github.com/phalt) and other [**PokéAPI contributors***](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.     
 *
 * The version of the OpenAPI document: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemDetailSprites } from './item-detail-sprites';
import { ItemFlingEffectSummary } from './item-fling-effect-summary';
import { ItemName } from './item-name';
import { AbilityDetailPokemonInnerPokemon } from './ability-detail-pokemon-inner-pokemon';
import { ItemCategorySummary } from './item-category-summary';
import { ItemDetailHeldByPokemonInner } from './item-detail-held-by-pokemon-inner';
import { ItemEffectText } from './item-effect-text';
import { ItemGameIndex } from './item-game-index';
import { ItemFlavorText } from './item-flavor-text';
import { ItemDetailBabyTriggerFor } from './item-detail-baby-trigger-for';
import { ItemDetailMachinesInner } from './item-detail-machines-inner';


export interface ItemDetail { 
    readonly id: number;
    name: string;
    cost?: number | null;
    fling_power?: number | null;
    fling_effect: ItemFlingEffectSummary;
    attributes: Array<AbilityDetailPokemonInnerPokemon>;
    category: ItemCategorySummary;
    effect_entries: Array<ItemEffectText>;
    flavor_text_entries: Array<ItemFlavorText>;
    game_indices: Array<ItemGameIndex>;
    names: Array<ItemName>;
    held_by_pokemon: Array<ItemDetailHeldByPokemonInner>;
    sprites: ItemDetailSprites;
    baby_trigger_for: ItemDetailBabyTriggerFor;
    machines: Array<ItemDetailMachinesInner>;
}

