/**
 * Hephaestus API
 * API documentation for the Hephaestus application server.
 *
 * The version of the OpenAPI document: 0.9.0-rc.5
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LabelInfo } from './label-info';
import { RepositoryInfo } from './repository-info';
import { PullRequestBadPractice } from './pull-request-bad-practice';


export interface PullRequestWithBadPractices { 
    id: number;
    number: number;
    title: string;
    state: PullRequestWithBadPractices.StateEnum;
    isDraft: boolean;
    isMerged: boolean;
    labels: Array<LabelInfo>;
    repository: RepositoryInfo;
    additions: number;
    deletions: number;
    htmlUrl: string;
    createdAt: string;
    updatedAt: string;
    badPracticeSummary: string;
    badPractices: Array<PullRequestBadPractice>;
    oldBadPractices: Array<PullRequestBadPractice>;
}
export namespace PullRequestWithBadPractices {
    export type StateEnum = 'OPEN' | 'CLOSED';
    export const StateEnum = {
        Open: 'OPEN' as StateEnum,
        Closed: 'CLOSED' as StateEnum
    };
}


