/**
 * Hephaestus API
 * API documentation for the Hephaestus application server.
 *
 * The version of the OpenAPI document: 0.9.0-rc.10
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LabelInfo } from './label-info';
import { RepositoryInfo } from './repository-info';
import { UserInfo } from './user-info';


export interface PullRequestInfo { 
    additions: number;
    assignees?: Array<UserInfo>;
    author?: UserInfo;
    closedAt?: string;
    commentsCount: number;
    createdAt?: string;
    deletions: number;
    htmlUrl: string;
    id: number;
    isDraft: boolean;
    isMerged: boolean;
    labels?: Array<LabelInfo>;
    mergedAt?: string;
    number: number;
    repository?: RepositoryInfo;
    state: PullRequestInfo.StateEnum;
    title: string;
    updatedAt?: string;
}
export namespace PullRequestInfo {
    export type StateEnum = 'OPEN' | 'CLOSED';
    export const StateEnum = {
        Open: 'OPEN' as StateEnum,
        Closed: 'CLOSED' as StateEnum
    };
}


