/**
 * Hephaestus API
 * API documentation for the Hephaestus application server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { PullRequest } from './pull-request';


export interface PullRequestReview { 
    id?: number;
    createdAt?: string;
    updatedAt?: string;
    author?: User;
    state: PullRequestReview.StateEnum;
    submittedAt?: string;
    pullRequest?: PullRequest;
}
export namespace PullRequestReview {
    export type StateEnum = 'COMMENTED' | 'APPROVED' | 'CHANGES_REQUESTED' | 'DISMISSED';
    export const StateEnum = {
        Commented: 'COMMENTED' as StateEnum,
        Approved: 'APPROVED' as StateEnum,
        ChangesRequested: 'CHANGES_REQUESTED' as StateEnum,
        Dismissed: 'DISMISSED' as StateEnum
    };
}


