/**
 * Hephaestus API
 * API documentation for the Hephaestus application server.
 *
 * The version of the OpenAPI document: 0.9.0-rc.10
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tool input start event.
 */
export interface StreamToolInputStartPart { 
    dynamic?: boolean | null;
    providerExecuted?: boolean | null;
    toolCallId: string;
    toolName: string;
    type?: string;
}

