/**
 * Hephaestus API
 * API documentation for the Hephaestus application server.
 *
 * The version of the OpenAPI document: 0.9.0-rc.9
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tool input error event (signals an error occurred while preparing input).  Mirrors AI SDK \'tool-input-error\' chunk. For non-dynamic tools, the server should record an \'output-error\' tool UI part where rawInput may be used for diagnostics.
 */
export interface StreamToolInputErrorPart { 
    dynamic?: boolean | null;
    errorText: string;
    input: any | null;
    providerExecuted?: boolean | null;
    providerMetadata?: object | null;
    toolCallId: string;
    toolName: string;
    type?: string;
}

