/**
 * Hephaestus API
 * API documentation for the Hephaestus application server.
 *
 * The version of the OpenAPI document: 0.9.0-rc.10
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileUIPart } from './file-ui-part';
import { SourceUrlUIPart } from './source-url-ui-part';
import { ToolOutputErrorPart } from './tool-output-error-part';
import { SourceDocumentUIPart } from './source-document-ui-part';
import { DataUIPart } from './data-ui-part';
import { StepStartUIPart } from './step-start-ui-part';
import { ReasoningUIPart } from './reasoning-ui-part';
import { TextUIPart } from './text-ui-part';
import { ToolInputAvailablePart } from './tool-input-available-part';
import { ToolOutputAvailablePart } from './tool-output-available-part';
import { ToolInputStreamingPart } from './tool-input-streaming-part';


export interface UIMessagePartsInner { 
    providerMetadata?: object;
    state: string;
    text: string;
    type: string;
    input: object;
    providerExecuted?: boolean;
    toolCallId: string;
    callProviderMetadata?: object;
    output: object;
    errorText: string;
    sourceId: string;
    title: string;
    url: string;
    filename?: string;
    mediaType: string;
    data: any | null;
    id?: string;
}

