openapi: 3.0.1
info:
  contact:
    email: felixtj.dietrich@tum.de
    name: Felix T.J. Dietrich
  description: API documentation for the Hephaestus intelligence service.
  license:
    name: MIT License
    url: https://github.com/ls1intum/Hephaestus/blob/develop/LICENSE
  title: Hephaestus API
  version: 0.0.1
servers:
- description: Local development server
  url: http://localhost:8080
paths:
  /chat:
    post:
      operationId: chatWithLLM
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
          description: Successful response from LLM
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal Server Error
      summary: Chat with LLM
      x-content-type: application/json
      x-accepts:
      - application/json
components:
  schemas:
    ChatRequest:
      example:
        message: message
      properties:
        message:
          description: The message to be sent to the LLM
          type: string
      required:
      - message
      type: object
    ChatResponse:
      example:
        response: response
      properties:
        response:
          description: The response generated by the LLM
          type: string
      required:
      - response
      type: object
    ErrorResponse:
      example:
        detail: detail
      properties:
        detail:
          description: Error message in case of failure
          type: string
      type: object

