/**
 * Hephaestus API
 * API documentation for the Hephaestus application server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AdminConfig } from '../model/models';
import { UserDTO } from '../model/models';
import { UserInfoDto } from '../model/models';
import { UserTeamsDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param login 
     * @param teamId 
     */
    addTeamToUser(login: string, teamId: number, extraHttpRequestParams?: any): Observable<UserDTO>;

    /**
     * 
     * 
     */
    admin(extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     */
    getConfig(extraHttpRequestParams?: any): Observable<AdminConfig>;

    /**
     * 
     * 
     */
    getGretting(extraHttpRequestParams?: any): Observable<UserInfoDto>;

    /**
     * 
     * 
     */
    getUsersAsAdmin(extraHttpRequestParams?: any): Observable<Array<UserTeamsDTO>>;

    /**
     * 
     * 
     * @param requestBody 
     */
    updateRepositories(requestBody: Array<string>, extraHttpRequestParams?: any): Observable<Set<string>>;

}
