export * from './activity.service';
import { ActivityService } from './activity.service';
export * from './activity.serviceInterface';
export * from './chat.service';
import { ChatService } from './chat.service';
export * from './chat.serviceInterface';
export * from './chat-mes.service';
import { ChatMesService } from './chat-mes.service';
export * from './chat-mes.serviceInterface';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './default.serviceInterface';
export * from './leaderboard.service';
import { LeaderboardService } from './leaderboard.service';
export * from './leaderboard.serviceInterface';
export * from './meta.service';
import { MetaService } from './meta.service';
export * from './meta.serviceInterface';
export * from './team.service';
import { TeamService } from './team.service';
export * from './team.serviceInterface';
export * from './team-v2.service';
import { TeamV2Service } from './team-v2.service';
export * from './team-v2.serviceInterface';
export * from './user.service';
import { UserService } from './user.service';
export * from './user.serviceInterface';
export * from './workspace.service';
import { WorkspaceService } from './workspace.service';
export * from './workspace.serviceInterface';
export const APIS = [ActivityService, ChatService, ChatMesService, DefaultService, LeaderboardService, MetaService, TeamService, TeamV2Service, UserService, WorkspaceService];
