/**
 * PokéAPI
 * All the Pokémon data you\'ll ever need in one place, easily accessible through a modern free open-source RESTful API.  ## What is this?  This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.  We\'ve covered everything from Pokémon to Berry Flavors.  ## Where do I start?  We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.  This API will always be publicly available and will never require any extensive setup process to consume.  Created by [**Paul Hallett**(]https://github.com/phalt) and other [**PokéAPI contributors***](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.     
 *
 * The version of the OpenAPI document: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ContestEffectDetail } from '../model/models';
import { ContestTypeDetail } from '../model/models';
import { PaginatedContestEffectSummaryList } from '../model/models';
import { PaginatedContestTypeSummaryList } from '../model/models';
import { PaginatedSuperContestEffectSummaryList } from '../model/models';
import { SuperContestEffectDetail } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ContestsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List contest effects
     * Contest effects refer to the effects of moves when used in contests.
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property. 
     */
    contestEffectList(limit?: number, offset?: number, q?: string, extraHttpRequestParams?: any): Observable<PaginatedContestEffectSummaryList>;

    /**
     * Get contest effect
     * Contest effects refer to the effects of moves when used in contests.
     * @param id This parameter can be a string or an integer.
     */
    contestEffectRetrieve(id: string, extraHttpRequestParams?: any): Observable<ContestEffectDetail>;

    /**
     * List contest types
     * Contest types are categories judges used to weigh a Pokémon\&#39;s condition in Pokémon contests. Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Contest_condition) for greater detail.
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property. 
     */
    contestTypeList(limit?: number, offset?: number, q?: string, extraHttpRequestParams?: any): Observable<PaginatedContestTypeSummaryList>;

    /**
     * Get contest type
     * Contest types are categories judges used to weigh a Pokémon\&#39;s condition in Pokémon contests. Check out [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Contest_condition) for greater detail.
     * @param id This parameter can be a string or an integer.
     */
    contestTypeRetrieve(id: string, extraHttpRequestParams?: any): Observable<ContestTypeDetail>;

    /**
     * List super contest effects
     * Super contest effects refer to the effects of moves when used in super contests.
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property. 
     */
    superContestEffectList(limit?: number, offset?: number, q?: string, extraHttpRequestParams?: any): Observable<PaginatedSuperContestEffectSummaryList>;

    /**
     * Get super contest effect
     * Super contest effects refer to the effects of moves when used in super contests.
     * @param id This parameter can be a string or an integer.
     */
    superContestEffectRetrieve(id: string, extraHttpRequestParams?: any): Observable<SuperContestEffectDetail>;

}
