/**
 * PokéAPI
 * All the Pokémon data you\'ll ever need in one place, easily accessible through a modern free open-source RESTful API.  ## What is this?  This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.  We\'ve covered everything from Pokémon to Berry Flavors.  ## Where do I start?  We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.  This API will always be publicly available and will never require any extensive setup process to consume.  Created by [**Paul Hallett**(]https://github.com/phalt) and other [**PokéAPI contributors***](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.     
 *
 * The version of the OpenAPI document: 2.7.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { GenerationDetail } from '../model/models';
import { PaginatedGenerationSummaryList } from '../model/models';
import { PaginatedPokedexSummaryList } from '../model/models';
import { PaginatedVersionGroupSummaryList } from '../model/models';
import { PaginatedVersionSummaryList } from '../model/models';
import { PokedexDetail } from '../model/models';
import { VersionDetail } from '../model/models';
import { VersionGroupDetail } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GamesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * List genrations
     * A generation is a grouping of the Pokémon games that separates them based on the Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and Types that did not exist in the previous generation are released.
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property. 
     */
    generationList(limit?: number, offset?: number, q?: string, extraHttpRequestParams?: any): Observable<PaginatedGenerationSummaryList>;

    /**
     * Get genration
     * A generation is a grouping of the Pokémon games that separates them based on the Pokémon they include. In each generation, a new set of Pokémon, Moves, Abilities and Types that did not exist in the previous generation are released.
     * @param id This parameter can be a string or an integer.
     */
    generationRetrieve(id: string, extraHttpRequestParams?: any): Observable<GenerationDetail>;

    /**
     * List pokedex
     * A Pokédex is a handheld electronic encyclopedia device; one which is capable of recording and retaining information of the various Pokémon in a given region with the exception of the national dex and some smaller dexes related to portions of a region. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pokedex) for greater detail.
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property. 
     */
    pokedexList(limit?: number, offset?: number, q?: string, extraHttpRequestParams?: any): Observable<PaginatedPokedexSummaryList>;

    /**
     * Get pokedex
     * A Pokédex is a handheld electronic encyclopedia device; one which is capable of recording and retaining information of the various Pokémon in a given region with the exception of the national dex and some smaller dexes related to portions of a region. See [Bulbapedia](http://bulbapedia.bulbagarden.net/wiki/Pokedex) for greater detail.
     * @param id This parameter can be a string or an integer.
     */
    pokedexRetrieve(id: string, extraHttpRequestParams?: any): Observable<PokedexDetail>;

    /**
     * List version groups
     * Version groups categorize highly similar versions of the games.
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property. 
     */
    versionGroupList(limit?: number, offset?: number, q?: string, extraHttpRequestParams?: any): Observable<PaginatedVersionGroupSummaryList>;

    /**
     * Get version group
     * Version groups categorize highly similar versions of the games.
     * @param id This parameter can be a string or an integer.
     */
    versionGroupRetrieve(id: string, extraHttpRequestParams?: any): Observable<VersionGroupDetail>;

    /**
     * List versions
     * Versions of the games, e.g., Red, Blue or Yellow.
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param q &gt; Only available locally and not at [pokeapi.co](https://pokeapi.co/docs/v2) Case-insensitive query applied on the &#x60;name&#x60; property. 
     */
    versionList(limit?: number, offset?: number, q?: string, extraHttpRequestParams?: any): Observable<PaginatedVersionSummaryList>;

    /**
     * Get version
     * Versions of the games, e.g., Red, Blue or Yellow.
     * @param id This parameter can be a string or an integer.
     */
    versionRetrieve(id: string, extraHttpRequestParams?: any): Observable<VersionDetail>;

}
