@startuml
left to right direction
skinparam backgroundColor transparent
skinparam packageStyle rectangle

actor "Developer" as Dev
actor "Project Manager" as PM
actor "Scrum Master" as SMaster
actor "Product Owner" as PO
actor "QA Engineer" as QA
actor "Security Analyst" as Sec

actor "Team Member" as TM

TM <|-up- Sec
TM <|-up- QA
TM <|-up- Dev
TM <|-up- SMaster
TM <|-up- PM
TM <|-up- PO

rectangle "Hephaestus System" {
  usecase "Provide Training & Onboarding" as PTO
  usecase "Facilitate Collaboration" as FC
  usecase "Enhance Security Practices" as ESP
  usecase "Streamline Maintenance" as SM
  usecase "Optimize Testing & Integration" as OT
  usecase "Support Implementation" as SI
  usecase "Maintain Documentation" as MD
  usecase "Assist Design" as AD
  usecase "Enhance Analysis" as EA
  usecase "Support Planning" as SP
}

TM --> PTO
TM --> FC
TM --> ESP
TM --> SM
TM --> OT
TM --> SI
TM --> MD
TM --> AD
TM --> EA
TM --> SP
@enduml