/*
 * Hephaestus Intelligence Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document is defined in server/intelligence-service/openapi.yaml.
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.in.www1.hephaestus.intelligenceservice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.tum.in.www1.hephaestus.intelligenceservice.model.BadPractice;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.hibernate.validator.constraints.*;

/**
 * BadPracticeResult
 */
@JsonPropertyOrder({
  BadPracticeResult.JSON_PROPERTY_BAD_PRACTICE_SUMMARY,
  BadPracticeResult.JSON_PROPERTY_BAD_PRACTICES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.7.0")
@SuppressWarnings("unused")
public class BadPracticeResult {
  public static final String JSON_PROPERTY_BAD_PRACTICE_SUMMARY = "badPracticeSummary";
  private String badPracticeSummary;

  public static final String JSON_PROPERTY_BAD_PRACTICES = "badPractices";
  private List<BadPractice> badPractices = new ArrayList<>();

  public BadPracticeResult() {
  }

  public BadPracticeResult badPracticeSummary(String badPracticeSummary) {
    
    this.badPracticeSummary = badPracticeSummary;
    return this;
  }

  /**
   * Get badPracticeSummary
   * @return badPracticeSummary
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BAD_PRACTICE_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBadPracticeSummary() {
    return badPracticeSummary;
  }


  @JsonProperty(JSON_PROPERTY_BAD_PRACTICE_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBadPracticeSummary(String badPracticeSummary) {
    this.badPracticeSummary = badPracticeSummary;
  }

  public BadPracticeResult badPractices(List<BadPractice> badPractices) {
    
    this.badPractices = badPractices;
    return this;
  }

  public BadPracticeResult addBadPracticesItem(BadPractice badPracticesItem) {
    if (this.badPractices == null) {
      this.badPractices = new ArrayList<>();
    }
    this.badPractices.add(badPracticesItem);
    return this;
  }

  /**
   * Get badPractices
   * @return badPractices
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BAD_PRACTICES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<BadPractice> getBadPractices() {
    return badPractices;
  }


  @JsonProperty(JSON_PROPERTY_BAD_PRACTICES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBadPractices(List<BadPractice> badPractices) {
    this.badPractices = badPractices;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BadPracticeResult badPracticeResult = (BadPracticeResult) o;
    return Objects.equals(this.badPracticeSummary, badPracticeResult.badPracticeSummary) &&
        Objects.equals(this.badPractices, badPracticeResult.badPractices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(badPracticeSummary, badPractices);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BadPracticeResult {\n");
    sb.append("    badPracticeSummary: ").append(toIndentedString(badPracticeSummary)).append("\n");
    sb.append("    badPractices: ").append(toIndentedString(badPractices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

