/*
 * Hephaestus Intelligence Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document is defined in server/intelligence-service/openapi.yaml.
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.in.www1.hephaestus.intelligenceservice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.tum.in.www1.hephaestus.intelligenceservice.model.ChatThreadSummary;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.hibernate.validator.constraints.*;

/**
 * ChatThreadGroup
 */
@JsonPropertyOrder({
  ChatThreadGroup.JSON_PROPERTY_GROUP_NAME,
  ChatThreadGroup.JSON_PROPERTY_THREADS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.7.0")
@SuppressWarnings("all")
public class ChatThreadGroup {
  public static final String JSON_PROPERTY_GROUP_NAME = "groupName";
  private String groupName;

  public static final String JSON_PROPERTY_THREADS = "threads";
  private List<ChatThreadSummary> threads = new ArrayList<>();

  public ChatThreadGroup() {
  }

  public ChatThreadGroup groupName(String groupName) {
    
    this.groupName = groupName;
    return this;
  }

  /**
   * Get groupName
   * @return groupName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GROUP_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getGroupName() {
    return groupName;
  }


  @JsonProperty(JSON_PROPERTY_GROUP_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public ChatThreadGroup threads(List<ChatThreadSummary> threads) {
    
    this.threads = threads;
    return this;
  }

  public ChatThreadGroup addThreadsItem(ChatThreadSummary threadsItem) {
    if (this.threads == null) {
      this.threads = new ArrayList<>();
    }
    this.threads.add(threadsItem);
    return this;
  }

  /**
   * Get threads
   * @return threads
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_THREADS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ChatThreadSummary> getThreads() {
    return threads;
  }


  @JsonProperty(JSON_PROPERTY_THREADS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setThreads(List<ChatThreadSummary> threads) {
    this.threads = threads;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChatThreadGroup chatThreadGroup = (ChatThreadGroup) o;
    return Objects.equals(this.groupName, chatThreadGroup.groupName) &&
        Objects.equals(this.threads, chatThreadGroup.threads);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupName, threads);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChatThreadGroup {\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    threads: ").append(toIndentedString(threads)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

