/*
 * Hephaestus Intelligence Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0-rc.27
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.in.www1.hephaestus.intelligenceservice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.hibernate.validator.constraints.*;

/**
 * MentorChatPost200ResponseAnyOf8
 */
@JsonPropertyOrder({
  MentorChatPost200ResponseAnyOf8.JSON_PROPERTY_TYPE,
  MentorChatPost200ResponseAnyOf8.JSON_PROPERTY_TOOL_CALL_ID,
  MentorChatPost200ResponseAnyOf8.JSON_PROPERTY_OUTPUT,
  MentorChatPost200ResponseAnyOf8.JSON_PROPERTY_PROVIDER_EXECUTED,
  MentorChatPost200ResponseAnyOf8.JSON_PROPERTY_DYNAMIC
})
@JsonTypeName("_mentor_chat_post_200_response_anyOf_8")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.7.0")
public class MentorChatPost200ResponseAnyOf8 {
  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    TOOL_OUTPUT_AVAILABLE("tool-output-available");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  private TypeEnum type;

  public static final String JSON_PROPERTY_TOOL_CALL_ID = "toolCallId";
  private String toolCallId;

  public static final String JSON_PROPERTY_OUTPUT = "output";
  private JsonNullable<Object> output = JsonNullable.<Object>of(null);

  public static final String JSON_PROPERTY_PROVIDER_EXECUTED = "providerExecuted";
  private Boolean providerExecuted;

  public static final String JSON_PROPERTY_DYNAMIC = "dynamic";
  private Boolean dynamic;

  public MentorChatPost200ResponseAnyOf8() {
  }

  public MentorChatPost200ResponseAnyOf8 type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(TypeEnum type) {
    this.type = type;
  }

  public MentorChatPost200ResponseAnyOf8 toolCallId(String toolCallId) {
    
    this.toolCallId = toolCallId;
    return this;
  }

  /**
   * Get toolCallId
   * @return toolCallId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOOL_CALL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToolCallId() {
    return toolCallId;
  }


  @JsonProperty(JSON_PROPERTY_TOOL_CALL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToolCallId(String toolCallId) {
    this.toolCallId = toolCallId;
  }

  public MentorChatPost200ResponseAnyOf8 output(Object output) {
    this.output = JsonNullable.<Object>of(output);
    
    return this;
  }

  /**
   * Get output
   * @return output
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Object getOutput() {
        return output.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OUTPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Object> getOutput_JsonNullable() {
    return output;
  }
  
  @JsonProperty(JSON_PROPERTY_OUTPUT)
  public void setOutput_JsonNullable(JsonNullable<Object> output) {
    this.output = output;
  }

  public void setOutput(Object output) {
    this.output = JsonNullable.<Object>of(output);
  }

  public MentorChatPost200ResponseAnyOf8 providerExecuted(Boolean providerExecuted) {
    
    this.providerExecuted = providerExecuted;
    return this;
  }

  /**
   * Get providerExecuted
   * @return providerExecuted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVIDER_EXECUTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getProviderExecuted() {
    return providerExecuted;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER_EXECUTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderExecuted(Boolean providerExecuted) {
    this.providerExecuted = providerExecuted;
  }

  public MentorChatPost200ResponseAnyOf8 dynamic(Boolean dynamic) {
    
    this.dynamic = dynamic;
    return this;
  }

  /**
   * Get dynamic
   * @return dynamic
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DYNAMIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getDynamic() {
    return dynamic;
  }


  @JsonProperty(JSON_PROPERTY_DYNAMIC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDynamic(Boolean dynamic) {
    this.dynamic = dynamic;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MentorChatPost200ResponseAnyOf8 mentorChatPost200ResponseAnyOf8 = (MentorChatPost200ResponseAnyOf8) o;
    return Objects.equals(this.type, mentorChatPost200ResponseAnyOf8.type) &&
        Objects.equals(this.toolCallId, mentorChatPost200ResponseAnyOf8.toolCallId) &&
        equalsNullable(this.output, mentorChatPost200ResponseAnyOf8.output) &&
        Objects.equals(this.providerExecuted, mentorChatPost200ResponseAnyOf8.providerExecuted) &&
        Objects.equals(this.dynamic, mentorChatPost200ResponseAnyOf8.dynamic);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, toolCallId, hashCodeNullable(output), providerExecuted, dynamic);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MentorChatPost200ResponseAnyOf8 {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    toolCallId: ").append(toIndentedString(toolCallId)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    providerExecuted: ").append(toIndentedString(providerExecuted)).append("\n");
    sb.append("    dynamic: ").append(toIndentedString(dynamic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

