/*
 * Hephaestus Intelligence Service API
 * API documentation for the Hephaestus Intelligence Service.
 *
 * The version of the OpenAPI document: 0.9.0-rc.5
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.in.www1.hephaestus.intelligenceservice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.hibernate.validator.constraints.*;

/**
 * Tool input available event.
 */
@JsonPropertyOrder({
  StreamToolInputAvailablePart.JSON_PROPERTY_INPUT,
  StreamToolInputAvailablePart.JSON_PROPERTY_TOOL_CALL_ID,
  StreamToolInputAvailablePart.JSON_PROPERTY_TOOL_NAME,
  StreamToolInputAvailablePart.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.7.0")
public class StreamToolInputAvailablePart {
  public static final String JSON_PROPERTY_INPUT = "input";
  private Object input;

  public static final String JSON_PROPERTY_TOOL_CALL_ID = "toolCallId";
  private String toolCallId;

  public static final String JSON_PROPERTY_TOOL_NAME = "toolName";
  private String toolName;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type = "tool-input-available";

  public StreamToolInputAvailablePart() {
  }

  public StreamToolInputAvailablePart input(Object input) {
    
    this.input = input;
    return this;
  }

  /**
   * Get input
   * @return input
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INPUT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getInput() {
    return input;
  }


  @JsonProperty(JSON_PROPERTY_INPUT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInput(Object input) {
    this.input = input;
  }

  public StreamToolInputAvailablePart toolCallId(String toolCallId) {
    
    this.toolCallId = toolCallId;
    return this;
  }

  /**
   * Get toolCallId
   * @return toolCallId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOOL_CALL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToolCallId() {
    return toolCallId;
  }


  @JsonProperty(JSON_PROPERTY_TOOL_CALL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToolCallId(String toolCallId) {
    this.toolCallId = toolCallId;
  }

  public StreamToolInputAvailablePart toolName(String toolName) {
    
    this.toolName = toolName;
    return this;
  }

  /**
   * Get toolName
   * @return toolName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOOL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToolName() {
    return toolName;
  }


  @JsonProperty(JSON_PROPERTY_TOOL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToolName(String toolName) {
    this.toolName = toolName;
  }

  public StreamToolInputAvailablePart type(String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StreamToolInputAvailablePart streamToolInputAvailablePart = (StreamToolInputAvailablePart) o;
    return Objects.equals(this.input, streamToolInputAvailablePart.input) &&
        Objects.equals(this.toolCallId, streamToolInputAvailablePart.toolCallId) &&
        Objects.equals(this.toolName, streamToolInputAvailablePart.toolName) &&
        Objects.equals(this.type, streamToolInputAvailablePart.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(input, toolCallId, toolName, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StreamToolInputAvailablePart {\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    toolCallId: ").append(toIndentedString(toolCallId)).append("\n");
    sb.append("    toolName: ").append(toIndentedString(toolName)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

