/*
 * Hephaestus Intelligence Service API
 * API documentation for the Hephaestus Intelligence Service.
 *
 * The version of the OpenAPI document: 0.9.0-rc.5
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.in.www1.hephaestus.intelligenceservice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.hibernate.validator.constraints.*;

/**
 * Tool output error event.
 */
@JsonPropertyOrder({
  StreamToolOutputErrorPart.JSON_PROPERTY_ERROR_TEXT,
  StreamToolOutputErrorPart.JSON_PROPERTY_TOOL_CALL_ID,
  StreamToolOutputErrorPart.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.7.0")
public class StreamToolOutputErrorPart {
  public static final String JSON_PROPERTY_ERROR_TEXT = "errorText";
  private String errorText;

  public static final String JSON_PROPERTY_TOOL_CALL_ID = "toolCallId";
  private String toolCallId;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type = "tool-output-error";

  public StreamToolOutputErrorPart() {
  }

  public StreamToolOutputErrorPart errorText(String errorText) {
    
    this.errorText = errorText;
    return this;
  }

  /**
   * Get errorText
   * @return errorText
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ERROR_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getErrorText() {
    return errorText;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setErrorText(String errorText) {
    this.errorText = errorText;
  }

  public StreamToolOutputErrorPart toolCallId(String toolCallId) {
    
    this.toolCallId = toolCallId;
    return this;
  }

  /**
   * Get toolCallId
   * @return toolCallId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOOL_CALL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToolCallId() {
    return toolCallId;
  }


  @JsonProperty(JSON_PROPERTY_TOOL_CALL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToolCallId(String toolCallId) {
    this.toolCallId = toolCallId;
  }

  public StreamToolOutputErrorPart type(String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StreamToolOutputErrorPart streamToolOutputErrorPart = (StreamToolOutputErrorPart) o;
    return Objects.equals(this.errorText, streamToolOutputErrorPart.errorText) &&
        Objects.equals(this.toolCallId, streamToolOutputErrorPart.toolCallId) &&
        Objects.equals(this.type, streamToolOutputErrorPart.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorText, toolCallId, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StreamToolOutputErrorPart {\n");
    sb.append("    errorText: ").append(toIndentedString(errorText)).append("\n");
    sb.append("    toolCallId: ").append(toIndentedString(toolCallId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

