/*
 * Hephaestus Intelligence Service API
 * API documentation for the Hephaestus Intelligence Service.
 *
 * The version of the OpenAPI document: 0.9.0-rc.5
 * Contact: felixtj.dietrich@tum.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.tum.in.www1.hephaestus.intelligenceservice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import de.tum.in.www1.hephaestus.intelligenceservice.model.Input;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import org.hibernate.validator.constraints.*;

/**
 * Tool part with input available.
 */
@JsonPropertyOrder({
  ToolInputAvailablePart.JSON_PROPERTY_INPUT,
  ToolInputAvailablePart.JSON_PROPERTY_PROVIDER_EXECUTED,
  ToolInputAvailablePart.JSON_PROPERTY_STATE,
  ToolInputAvailablePart.JSON_PROPERTY_TOOL_CALL_ID,
  ToolInputAvailablePart.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.7.0")
public class ToolInputAvailablePart {
  public static final String JSON_PROPERTY_INPUT = "input";
  private Input input;

  public static final String JSON_PROPERTY_PROVIDER_EXECUTED = "providerExecuted";
  private JsonNullable<Boolean> providerExecuted = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_STATE = "state";
  private String state;

  public static final String JSON_PROPERTY_TOOL_CALL_ID = "toolCallId";
  private String toolCallId;

  public static final String JSON_PROPERTY_TYPE = "type";
  private String type;

  public ToolInputAvailablePart() {
  }

  public ToolInputAvailablePart input(Input input) {
    
    this.input = input;
    return this;
  }

  /**
   * Get input
   * @return input
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INPUT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Input getInput() {
    return input;
  }


  @JsonProperty(JSON_PROPERTY_INPUT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInput(Input input) {
    this.input = input;
  }

  public ToolInputAvailablePart providerExecuted(Boolean providerExecuted) {
    this.providerExecuted = JsonNullable.<Boolean>of(providerExecuted);
    
    return this;
  }

  /**
   * Get providerExecuted
   * @return providerExecuted
   */
  @jakarta.annotation.Nullable
  @JsonIgnore

  public Boolean getProviderExecuted() {
        return providerExecuted.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROVIDER_EXECUTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getProviderExecuted_JsonNullable() {
    return providerExecuted;
  }
  
  @JsonProperty(JSON_PROPERTY_PROVIDER_EXECUTED)
  public void setProviderExecuted_JsonNullable(JsonNullable<Boolean> providerExecuted) {
    this.providerExecuted = providerExecuted;
  }

  public void setProviderExecuted(Boolean providerExecuted) {
    this.providerExecuted = JsonNullable.<Boolean>of(providerExecuted);
  }

  public ToolInputAvailablePart state(String state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(String state) {
    this.state = state;
  }

  public ToolInputAvailablePart toolCallId(String toolCallId) {
    
    this.toolCallId = toolCallId;
    return this;
  }

  /**
   * Get toolCallId
   * @return toolCallId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TOOL_CALL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getToolCallId() {
    return toolCallId;
  }


  @JsonProperty(JSON_PROPERTY_TOOL_CALL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToolCallId(String toolCallId) {
    this.toolCallId = toolCallId;
  }

  public ToolInputAvailablePart type(String type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(String type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ToolInputAvailablePart toolInputAvailablePart = (ToolInputAvailablePart) o;
    return Objects.equals(this.input, toolInputAvailablePart.input) &&
        equalsNullable(this.providerExecuted, toolInputAvailablePart.providerExecuted) &&
        Objects.equals(this.state, toolInputAvailablePart.state) &&
        Objects.equals(this.toolCallId, toolInputAvailablePart.toolCallId) &&
        Objects.equals(this.type, toolInputAvailablePart.type);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(input, hashCodeNullable(providerExecuted), state, toolCallId, type);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ToolInputAvailablePart {\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    providerExecuted: ").append(toIndentedString(providerExecuted)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    toolCallId: ").append(toIndentedString(toolCallId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

