name: CI/CD

on:
  push:
    branches: [ develop ]
    paths:
      - 'server/application-server/**'
      - '!server/application-server/src/main/java/de/tum/in/www1/hephaestus/intelligenceservice/**'
      - '.github/workflows/application-server-ci.yml'
  pull_request:
    branches: [ develop ]
    paths:
      - 'server/application-server/**'
      - '!server/application-server/src/main/java/de/tum/in/www1/hephaestus/intelligenceservice/**'
      - '.github/workflows/application-server-ci.yml'

defaults:
  run:
    working-directory: server/application-server

env:
  MAVEN_OPTS: -Xmx1024m -XX:+UseParallelGC
  TESTCONTAINERS_REUSE_ENABLE: true

jobs:
  # Code quality checks
  code-quality:
    name: Application Server / Code Quality
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for Prettier
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install formatting dependencies
        run: npm ci --production
        working-directory: .

      - name: Check Java code formatting
        run: npm run format:java:check
        working-directory: .
        continue-on-error: true

  # Unit tests - run independently
  unit-tests:
    name: Application Server / Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run unit tests
        run: |
          mvn test \
            -Dgroups="unit" \
            -T 1C \
            --batch-mode \
            --fail-at-end
        continue-on-error: true

      - name: Upload unit test results
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Unit Test Results
          path: server/application-server/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false

  # Architecture tests - run independently
  architecture-tests:
    name: Application Server / Architecture Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run architecture tests
        run: |
          mvn test \
            -Dtest="**/ArchitectureTest" \
            --batch-mode \
            --fail-at-end
        continue-on-error: true

      - name: Upload architecture test results
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Architecture Test Results
          path: server/application-server/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false

  # Integration tests - run independently with Testcontainers
  integration-tests:
    name: Application Server / Integration Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run integration tests
        run: |
          mvn test \
            -Dgroups="integration" \
            -T 1C \
            --batch-mode \
            --fail-at-end
        continue-on-error: true

      - name: Upload integration test results
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: Integration Test Results
          path: server/application-server/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: false
