name: Build Docker Images

on:
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'CODE_OF_CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'SECURITY.md'
    - 'project.code-workspace'
    - 'docs/**'
    - 'keycloakify/**'
    - '.github/**'
    - '!.github/workflows/build-and-push-docker.yml'
  push:
    branches:
      - develop
      - release/*
  release:
    types:
      - created

# Global concurrency for the entire workflow
concurrency:
  group: docker-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.name }}
    if: github.actor != 'dependabot[bot]'
    runs-on: blacksmith-16vcpu-ubuntu-2204
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Webapp
            dockerfile: ./webapp/Dockerfile
            image: ghcr.io/ls1intum/hephaestus/webapp
            context: ./webapp
          - name: Application Server
            dockerfile: ./server/application-server/Dockerfile
            image: ghcr.io/ls1intum/hephaestus/application-server
            context: ./server/application-server
          - name: Intelligence Service
            dockerfile: ./server/intelligence-service/Dockerfile
            image: ghcr.io/ls1intum/hephaestus/intelligence-service
            context: ./server/intelligence-service
          - name: Webhook Ingest
            dockerfile: ./server/webhook-ingest/Dockerfile
            image: ghcr.io/ls1intum/hephaestus/webhook-ingest
            context: ./server/webhook-ingest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
  
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: "network=default"
          buildkitd-flags: "--allow-insecure-entitlement security.insecure"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get branch or tag name
        id: get-branch-or-tag
        run: echo "BRANCH_OR_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix=,format=long

      # Build multi-arch image directly with Blacksmith
      - name: Build and push multi-architecture Docker image
        id: build
        uses: useblacksmith/build-push-action@v1
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          network: default
