name: Build Docker Images

on:
  pull_request:
    paths-ignore:
    - 'README.md'
    - 'CODE_OF_CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'SECURITY.md'
    - 'docs/**'
    - 'keycloakify/**'
    - '.github/**'
    - '!.github/workflows/build-and-push-docker.yml'
  push:
    branches:
      - develop
      - release/*
  release:
    types:
      - created

jobs:
  build:
    if: github.actor != 'dependabot[bot]'
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./webapp/Dockerfile
            image: ghcr.io/ls1intum/hephaestus/webapp
            context: ./webapp
          - dockerfile: ./server/intelligence-service/Dockerfile
            image: ghcr.io/ls1intum/hephaestus/intelligence-service
            context: ./server/intelligence-service
          - dockerfile: ./server/webhook-ingest/Dockerfile
            image: ghcr.io/ls1intum/hephaestus/webhook-ingest
            context: ./server/webhook-ingest
          - dockerfile: ./server/application-server/Dockerfile
            image: ghcr.io/ls1intum/hephaestus/application-server
            context: ./server/application-server
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      image-name: ${{ matrix.image }}
      docker-file: ${{ matrix.dockerfile }}
      docker-context: ${{ matrix.context }}
