name: Build and Push Docker Image natively
run-name: Build and Push Docker Image natively

on:
  workflow_call:
    inputs:
      image-name:
        type: string
        default: ${{ github.repository }}
        description: "The name for the docker image (Default: Repository name)"
      docker-file:
        type: string
        default: Dockerfile
        description: "The path to the Dockerfile (Default: ./Dockerfile)"
      docker-context:
        type: string
        default: .
        description: "The context for the Docker build (Default: .)"
      build-args:
        type: string
        description: "List of additional build contexts (e.g., name=path)"
        required: false
      labels:
        type: string
        description: "Label that should be appended to the image"
        required: false
      tags:
        type: string
        description: "Tags that should be appended to the image"
        required: false
      registry:
        type: string
        default: ghcr.io
        description: "The registry to push the image to (Default: ghcr.io)"
      network:
        type: string
        default: default
        description: "Networking mode for the RUN instructions during build (Default: default)"
    outputs:
      image_tag: 
        description: "The tag of the image that was built"
        value: ${{ jobs.merge.outputs.image_tag }}
    
    secrets:
      registry-user:
        required: false
      registry-password:
        required: false

concurrency: 
  group: docker-build-${{ inputs.image-name }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build ${{ matrix.platform }} Docker Image for ${{ inputs.image-name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: blacksmith-8vcpu-ubuntu-2204
          - platform: linux/arm64
            runner: blacksmith-8vcpu-ubuntu-2204-arm
    runs-on: ${{ matrix.runner || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
  
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: "network=${{ inputs.network }}"
          buildkitd-flags: "--allow-insecure-entitlement security.insecure"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.registry-user || github.actor }}
          password: ${{ secrets.registry-password || secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.image-name }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ inputs.tags }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix=,format=long
      - name: Build and push Docker Image
        id: build
        uses: useblacksmith/build-push-action@v1
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.docker-file }}
          tags: ${{ steps.meta.outputs.tags || inputs.registry }}/${{ inputs.image-name }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ inputs.build-args }}
          platforms: ${{ matrix.platform }}
          push: true
          network: ${{ inputs.network }}
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          image="${{ inputs.image-name }}"
          echo "IMAGE_NAME=${image//\//-}" >> $GITHUB_ENV

  merge:
    name: Create and Push Multi-Arch Manifest
    runs-on: ubuntu-latest
    outputs: 
      image_tag: ${{ steps.output-image-tag.outputs.image_tag }}
    needs:
      - build
    steps:
      - name: Prepare
        run: |
          image="${{ inputs.image-name }}"
          echo "IMAGE_NAME=${image//\//-}" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: "--allow-insecure-entitlement security.insecure"

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.image-name }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ inputs.tags }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix=,format=long
          labels: |
            ${{ inputs.labels }}
      
      - name: Create multi-arch manifest
        run: |
          # Create the manifest
          docker manifest create ${{ inputs.registry }}/${{ inputs.image-name }}:latest \
            ${{ inputs.registry }}/${{ inputs.image-name }}:linux-amd64 \
            ${{ inputs.registry }}/${{ inputs.image-name }}:linux-arm64
            
          # Annotate with platform information
          docker manifest annotate ${{ inputs.registry }}/${{ inputs.image-name }}:latest \
            ${{ inputs.registry }}/${{ inputs.image-name }}:linux-amd64 --os linux --arch amd64
          docker manifest annotate ${{ inputs.registry }}/${{ inputs.image-name }}:latest \
            ${{ inputs.registry }}/${{ inputs.image-name }}:linux-arm64 --os linux --arch arm64
            
          # Push the manifest
          docker manifest push ${{ inputs.registry }}/${{ inputs.image-name }}:latest
          
      - id: output-image-tag
        run: |
          echo "image_tag=${{ steps.meta.outputs.version }}" >> "$GITHUB_OUTPUT"