   name:  Check Java Client is Up-to-Date

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
     check-openapi:
       runs-on: ubuntu-latest
       steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
           java-version: '11'
           distribution: 'adopt'
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '16'
       - name: Install dependencies
         run: npm ci

       - name: Generate Java client
         run: npm run generate:java-client
       - name: Check for changes
         run: |
          git status
          if [[ `git status --porcelain` ]]; then
            echo "Changes detected in the generated client. Please regenerate and commit the changes."
            exit 1
          else
            echo "No changes detected in the generated client."
          fi