name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: "Image tag to deploy (default: pr-<number> if PR exists, latest for default branch)"
      deploy-app:
        type: boolean
        default: true
        description: (Re-)deploys the app components
      deploy-core:
        default: false
        type: boolean
        description: (Re-)deploys NATS, Keycloak, Webhook Inject is usually not necessary and might cause data gaps.

jobs:  
  deploy-app:
    if: ${{ github.event.inputs.deploy-app }}
    uses: ls1intum/.github/.github/workflows/deploy-docker-compose.yml@deployment-workflow
    with:
      environment: Production
      docker-compose-file: "./docker/compose.prod.app.yaml"
      main-image-name: ls1intum/hephaestus/application-server
      image-tag: ${{ inputs.image-tag }}
      env-file-name: .env.prod.app
    secrets: inherit
  
  deploy-core:
    if: ${{ github.event.inputs.deploy-core }}
    #TODO: Implement deployment of core
    runs-on: ubuntu-latest
    steps:
      - name: TODO
        run: echo "TODO - Implement deployment of core"