name: CI/CD

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
    paths:
      - 'server/application-server/**'
      - 'server/intelligence-service/**'
      - '.github/workflows/openapi-ci.yml'
  push:
    paths:
      - 'server/application-server/openapi.yaml'
      - 'server/intelligence-service/openapi.yaml'
      - 'webapp-react/src/api/**/*.gen.ts'
      - 'server/application-server/src/main/java/de/tum/in/www1/hephaestus/intelligenceservice/**'
    branches: [develop]
  workflow_dispatch:

jobs:
  # Intelligence Service spec validation
  intelligence-service-specs:
    name: Intelligence Service / Validate OpenAPI spec (add autocommit-openapi label to PR to auto-commit changes)
    runs-on: ubuntu-latest
    outputs:
      spec-changed: ${{ steps.check_spec_changes.outputs.spec_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Python dependencies
        working-directory: server/intelligence-service
        run: poetry lock && poetry install --no-interaction --no-root

      - name: Generate and validate OpenAPI specs
        working-directory: server/intelligence-service
        run: poetry run openapi

      - name: Check for spec changes
        id: check_spec_changes
        run: |
          echo "Checking for changes in OpenAPI spec..."
          git add server/intelligence-service/openapi.yaml
          if git diff --cached --quiet; then
            echo "No changes detected in OpenAPI spec."
            echo "spec_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in OpenAPI spec."
            git diff --cached
            echo "spec_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Upload OpenAPI specs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: intelligence-service-openapi-spec
          path: server/intelligence-service/openapi.yaml

  # Application Server spec validation
  application-server-specs:
    name: Application Server / Validate OpenAPI spec (add autocommit-openapi label to PR to auto-commit changes)
    runs-on: ubuntu-latest
    outputs:
      spec-changed: ${{ steps.check_spec_changes.outputs.spec_changed }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up directories
        working-directory: server/application-server
        run: |
          mkdir -p ./keycloak-data
          chmod -R 755 ./keycloak-data

      - name: Generate and validate OpenAPI specs
        working-directory: server/application-server
        run: mvn verify -DskipTests=true -Dapp.profiles=specs

      - name: Check for spec changes
        id: check_spec_changes
        run: |
          echo "Checking for changes in OpenAPI spec..."
          git add server/application-server/openapi.yaml
          if git diff --cached --quiet; then
            echo "No changes detected in OpenAPI spec."
            echo "spec_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in OpenAPI spec."
            git diff --cached
            echo "spec_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Upload OpenAPI specs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-server-openapi-spec
          path: server/application-server/openapi.yaml

  # Intelligence Service Java client generation (depends on spec validation)
  intelligence-service-client:
    name: Application Server / Validate Java API client (add autocommit-openapi label to PR to auto-commit changes)
    runs-on: ubuntu-latest
    needs: intelligence-service-specs
    outputs:
      client-changed: ${{ steps.check_changes.outputs.changes_detected }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false
          fetch-depth: 0

      - name: Download OpenAPI specs
        uses: actions/download-artifact@v4
        with:
          name: intelligence-service-openapi-spec
          path: server/intelligence-service/

      - name: Install dependencies
        run: npm install

      - name: Generate Java client for the intelligence service
        run: npm run generate:api:intelligence-service:client

      - name: Check for changes in the API
        id: check_changes
        run: |
          echo "Checking for changes in the API client directory..."
          git add .
          if git diff --cached --quiet; then
            echo "No changes detected in the API client directory."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in the API client directory."
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            git diff --cached
          fi

  # Application Server React client generation (depends on spec validation)
  application-server-client:
    name: Webapp (React) / Validate TypeScript API client (add autocommit-openapi label to PR to auto-commit changes)
    runs-on: ubuntu-latest
    needs: application-server-specs
    outputs:
      client-changed: ${{ steps.check_changes.outputs.changes_detected }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false
          fetch-depth: 0

      - name: Download OpenAPI specs
        uses: actions/download-artifact@v4
        with:
          name: application-server-openapi-spec
          path: server/application-server/

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Generate React client for the application server
        run: npm run generate:api:application-server:client-react

      - name: Check for changes in the API
        id: check_changes
        run: |
          echo "Checking for changes in the API client directory..."
          echo "Current git status:"
          git status
          echo "Current git diff:"
          git diff
          git add .
          echo "Git status after adding changes:"
          git status
          if git diff --cached --quiet; then
            echo "No changes detected in the API client directory."
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in the API client directory."
            echo "Staged changes:"
            git diff --cached
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          fi

  # Unified commit job - runs after both client generations complete
  commit-changes:
    name: OpenAPI / Commit All Changes (add autocommit-openapi label to PR to auto-commit changes)
    runs-on: ubuntu-latest
    needs: [intelligence-service-specs, application-server-specs, intelligence-service-client, application-server-client]
    if: |
      always() && 
      contains(github.event.pull_request.labels.*.name, 'autocommit-openapi') &&
      (
        needs.intelligence-service-specs.outputs.spec-changed == 'true' ||
        needs.application-server-specs.outputs.spec-changed == 'true' ||
        needs.intelligence-service-client.outputs.client-changed == 'true' ||
        needs.application-server-client.outputs.client-changed == 'true'
      )

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python 3.13 (for intelligence service spec regeneration)
        if: needs.intelligence-service-specs.outputs.spec-changed == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install Poetry (for intelligence service spec regeneration)
        if: needs.intelligence-service-specs.outputs.spec-changed == 'true'
        uses: snok/install-poetry@v1
        with:
          version: 2.1.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Install Python dependencies (for intelligence service spec regeneration)
        if: needs.intelligence-service-specs.outputs.spec-changed == 'true'
        working-directory: server/intelligence-service
        run: poetry lock && poetry install --no-interaction --no-root

      - name: Regenerate intelligence service OpenAPI specs
        if: needs.intelligence-service-specs.outputs.spec-changed == 'true'
        working-directory: server/intelligence-service
        run: poetry run openapi

      - name: Set up JDK 21 (for application server spec regeneration)
        if: needs.application-server-specs.outputs.spec-changed == 'true'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up directories (for application server spec regeneration)
        if: needs.application-server-specs.outputs.spec-changed == 'true'
        working-directory: server/application-server
        run: |
          mkdir -p ./keycloak-data
          chmod -R 755 ./keycloak-data

      - name: Regenerate application server OpenAPI specs
        if: needs.application-server-specs.outputs.spec-changed == 'true'
        working-directory: server/application-server
        run: mvn verify -DskipTests=true -Dapp.profiles=specs

      - name: Set up Node.js (for client regeneration)
        if: |
          needs.intelligence-service-client.outputs.client-changed == 'true' ||
          needs.application-server-client.outputs.client-changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies (for client regeneration)
        if: |
          needs.intelligence-service-client.outputs.client-changed == 'true' ||
          needs.application-server-client.outputs.client-changed == 'true'
        run: npm install

      - name: Regenerate intelligence service Java client
        if: needs.intelligence-service-client.outputs.client-changed == 'true'
        run: npm run generate:api:intelligence-service:client

      - name: Regenerate application server React client
        if: needs.application-server-client.outputs.client-changed == 'true'
        run: npm run generate:api:application-server:client-react

      - name: Check for any changes and commit
        run: |
          echo "Checking for any changes to commit..."
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            echo "Changes detected. Committing all OpenAPI updates..."
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            
            # Build commit message based on what changed
            COMMIT_MSG="chore: update OpenAPI specs and clients"
            COMMIT_BODY=""
            
            if [[ "${{ needs.intelligence-service-specs.outputs.spec-changed }}" == "true" ]]; then
              COMMIT_BODY="$COMMIT_BODY\n- Update intelligence service OpenAPI spec"
            fi
            
            if [[ "${{ needs.application-server-specs.outputs.spec-changed }}" == "true" ]]; then
              COMMIT_BODY="$COMMIT_BODY\n- Update application server OpenAPI spec"
            fi
            
            if [[ "${{ needs.intelligence-service-client.outputs.client-changed }}" == "true" ]]; then
              COMMIT_BODY="$COMMIT_BODY\n- Update intelligence service Java client"
            fi
            
            if [[ "${{ needs.application-server-client.outputs.client-changed }}" == "true" ]]; then
              COMMIT_BODY="$COMMIT_BODY\n- Update application server React client"
            fi
            
            git commit -a -m "$COMMIT_MSG$COMMIT_BODY"
            echo "CHANGES_COMMITTED=true" >> $GITHUB_ENV
          fi

      - name: Push changes
        if: env.CHANGES_COMMITTED == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: ${{ github.event.pull_request.head.ref  }}

      - name: Remove autocommit-openapi label
        run: |
          echo "Removing the autocommit-openapi label..."
          curl --silent --fail-with-body -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/autocommit-openapi
