name: OpenAPI Auto-commit

on:
  pull_request:
    types: [labeled]

env:
  NODE_VERSION: 22
  PYTHON_VERSION: 3.13
  JAVA_VERSION: 21

jobs:
  autocommit:
    name: Auto-commit OpenAPI changes
    runs-on: ubuntu-latest
    if: github.event.label.name == 'autocommit-openapi'
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup caches
        uses: ./.github/actions/setup-caches
        with:
          cache-type: openapi-validation
          os: ${{ runner.os }}

      - name: Install Node.js dependencies
        run: |
          # Install dependencies if not cached
          if [ ! -d "node_modules" ]; then
            npm ci --prefer-offline --no-audit
          fi

      - name: Install Python dependencies
        working-directory: server/intelligence-service
        run: |
          # Install dependencies if not cached
          if [ ! -d ".venv" ]; then
            poetry install --no-interaction --no-root
          fi

      - name: Setup Application Server directories
        working-directory: server/application-server
        run: |
          mkdir -p ./keycloak-data
          chmod -R 755 ./keycloak-data

      - name: Compile Application Server
        working-directory: server/application-server
        run: mvn compile -DskipTests --quiet

      - name: Generate OpenAPI specs and clients
        run: npm run generate:api

      - name: Commit and push changes
        id: commit
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add .
          
          if ! git diff --cached --quiet; then
            git commit -m "chore: update OpenAPI specs and clients [skip ci]"
            git push origin ${{ github.event.pull_request.head.ref }}
            echo "changes_committed=true" >> $GITHUB_OUTPUT
          else
            echo "changes_committed=false" >> $GITHUB_OUTPUT
          fi

      - name: Remove label and comment
        if: always()
        run: |
          # Remove the label
          curl -s -X DELETE \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels/autocommit-openapi"
          
          # Add comment
          if [[ "${{ steps.commit.outputs.changes_committed }}" == "true" ]]; then
            COMMENT="🤖 OpenAPI specs and clients have been automatically updated and committed."
          else
            COMMENT="🤖 No OpenAPI changes were needed - everything is already up to date."
          fi
          
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\":\"$COMMENT\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
