name: "PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  main:
    name: Validate title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (following conventional commits)
          types: |
            fix
            feat
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Configure which scopes are allowed for better organization
          scopes: |
            webapp
            webapp-react
            application-server
            intelligence-service
            webhook-ingest
            docs
            ci
            deps
            config
          # Configure that a scope should be provided for better categorization
          requireScope: false
          # Configure validation for the subject
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            should start with a lowercase character for consistency.
          # Allow work-in-progress PRs with [WIP] prefix
          wip: true
